import {style,qs,formatDuration} from './helpers.js';
export function mount(root){
 style();
 root.innerHTML='<section class="ut-page"><div class="ut-card"><div class="ut-head"><div class="ut-head-icon">timer</div><div><h2>Pomodoro Timer</h2><p>Focus, break, repeat. Your cycle count is saved during this session.</p></div></div><div class="ut-grid"><label class="ut-field"><span>Focus minutes</span><input data-focus type="number" min="1" max="120" value="25"></label><label class="ut-field"><span>Break minutes</span><input data-break type="number" min="1" max="60" value="5"></label></div><div class="ut-center"><div class="ut-pill" data-mode>Focus</div><div class="ut-big" data-time>25:00</div><p class="ut-note" data-cycle>Cycle 1</p></div><div class="ut-actions"><button class="primary" data-toggle>Start</button><button data-skip>Skip phase</button><button data-reset>Reset</button></div></div></section>';
 const f=qs(root,'[data-focus]'),b=qs(root,'[data-break]'),mode=qs(root,'[data-mode]'),time=qs(root,'[data-time]'),cycle=qs(root,'[data-cycle]');let running=false,sec=25*60,phase='focus',count=1,timer=null;
 function resetPhase(){sec=Number(f.value||25)*60;phase='focus';count=1;mode.textContent='Focus';cycle.textContent='Cycle 1';draw()}
 function draw(){time.textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
 function tick(){if(sec>0){sec--;draw();return}phase=phase==='focus'?'break':'focus';if(phase==='focus')count++;sec=(phase==='focus'?Number(f.value||25):Number(b.value||5))*60;mode.textContent=phase==='focus'?'Focus':'Break';cycle.textContent='Cycle '+count;draw()}
 qs(root,'[data-toggle]').onclick=()=>{if(running){clearInterval(timer);timer=null;running=false;qs(root,'[data-toggle]').textContent='Start'}else{timer=setInterval(tick,1000);running=true;qs(root,'[data-toggle]').textContent='Pause'}};
 qs(root,'[data-skip]').onclick=tick;qs(root,'[data-reset]').onclick=()=>{clearInterval(timer);timer=null;running=false;qs(root,'[data-toggle]').textContent='Start';resetPhase()};
 f.onchange=()=>{if(!running&&phase==='focus'){sec=Number(f.value||25)*60;draw()}};b.onchange=()=>{if(!running&&phase==='break'){sec=Number(b.value||5)*60;draw()}};resetPhase();
}