const STYLE_ID='toolzy-developer-suite-styles';
const $=(root,sel)=>root.querySelector(sel);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy=async text=>{try{await navigator.clipboard.writeText(text);return true}catch{return false}};
function styles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.dev-suite{display:grid;gap:16px}.dev-panel{background:var(--surface,#fff);border:1px solid var(--border,#ddd);border-radius:24px;padding:18px;box-shadow:0 2px 8px rgba(0,0,0,.04)}
.dev-toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px}.dev-toolbar .spacer{flex:1}.dev-grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}.dev-grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}
.dev-editor{width:100%;min-height:260px;resize:vertical;font:500 14px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;background:var(--surface-container,#f6f6f6);color:var(--text,#171717);border:1px solid var(--border,#ddd);border-radius:18px;padding:16px;box-sizing:border-box;outline:none}.dev-editor:focus{border-color:var(--primary,#6750a4);box-shadow:0 0 0 3px color-mix(in srgb,var(--primary,#6750a4) 15%,transparent)}
.dev-output{min-height:120px;white-space:pre-wrap;overflow:auto;font:500 13px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;background:var(--surface-container,#f6f6f6);border:1px solid var(--border,#ddd);border-radius:18px;padding:16px}.dev-output.ok{border-color:#54a66b}.dev-output.error{border-color:#c85b5b}.dev-label{font-size:12px;font-weight:700;letter-spacing:.04em;text-transform:uppercase;opacity:.7;margin:0 0 8px}.dev-stat{font-size:28px;font-weight:750}.dev-muted{opacity:.68}.dev-row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.dev-input{width:100%;box-sizing:border-box;border:1px solid var(--border,#ddd);border-radius:14px;padding:12px 14px;background:var(--surface-container,#f6f6f6);color:inherit;outline:none}.dev-input:focus{border-color:var(--primary,#6750a4)}.dev-select{min-width:180px}.dev-result-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.dev-result{padding:14px;border:1px solid var(--border,#ddd);border-radius:16px;background:var(--surface-container,#f6f6f6)}.dev-code{font:500 13px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap}.dev-preview{min-height:260px;padding:18px;border:1px solid var(--border,#ddd);border-radius:18px;overflow:auto;background:var(--surface,#fff)}.dev-diff{font:500 13px/1.6 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap}.dev-add{color:#08783e;background:rgba(30,160,80,.09)}.dev-del{color:#a52626;background:rgba(200,50,50,.09)}.dev-chip{display:inline-flex;padding:6px 10px;border-radius:999px;background:var(--surface-container,#f6f6f6);border:1px solid var(--border,#ddd);font-size:12px}.dev-error{color:#a52626}.dev-success{color:#08783e}@media(max-width:760px){.dev-grid2,.dev-grid3{grid-template-columns:1fr}.dev-panel{padding:14px;border-radius:20px}}
`;document.head.appendChild(s)}
function shell(title,desc,body){return `<div class="dev-suite"><div class="dev-panel"><div class="dev-toolbar"><div><div class="dev-label">Developer tool</div><h2 style="margin:0">${esc(title)}</h2><p class="dev-muted" style="margin:4px 0 0">${esc(desc)}</p></div></div>${body}</div></div>`}
function buttons(){return `<button class="primary" data-action="run">Run</button><button class="secondary" data-action="copy">Copy output</button><button class="secondary" data-action="clear">Clear</button>`}
function twoText(placeholderA,placeholderB='Output'){return `<div class="dev-grid2"><div><p class="dev-label">Input</p><textarea class="dev-editor" data-input placeholder="${esc(placeholderA)}"></textarea></div><div><p class="dev-label">Output</p><pre class="dev-output" data-output>${esc(placeholderB)}</pre></div></div><div class="dev-toolbar">${buttons()}</div>`}
function setOut(root,text,ok=true){const o=$(root,'[data-output]');o.textContent=text;o.classList.toggle('ok',ok);o.classList.toggle('error',!ok)}
function bindBasic(root,run){$(root,'[data-action="run"]').onclick=run;$(root,'[data-action="clear"]').onclick=()=>{root.querySelectorAll('textarea,input').forEach(x=>x.value='');setOut(root,'')};$(root,'[data-action="copy"]').onclick=async()=>{await copy($(root,'[data-output]').textContent)}}
function formatJson(v,space=2){return JSON.stringify(JSON.parse(v),null,space)}
function simpleYaml(obj,indent=0){const pad=' '.repeat(indent);if(obj===null)return 'null';if(typeof obj!=='object')return typeof obj==='string'?(JSON.stringify(obj)) : String(obj);let out='';if(Array.isArray(obj)){for(const v of obj){if(v&&typeof v==='object')out+=`${pad}-\n${simpleYaml(v,indent+2).split('\n').map((x,i)=>i?`${' '.repeat(2)}${x}`:x).join('\n')}\n`;else out+=`${pad}- ${simpleYaml(v,0)}\n`;}return out.trimEnd()}for(const [k,v] of Object.entries(obj)){if(v&&typeof v==='object')out+=`${pad}${k}:\n${simpleYaml(v,indent+2)}\n`;else out+=`${pad}${k}: ${simpleYaml(v,0)}\n`}return out.trimEnd()}
function yamlToJson(s){const lines=s.split(/\r?\n/).filter(x=>x.trim()&&!x.trim().startsWith('#'));const root={};const stack=[{indent:-1,obj:root}];for(const line of lines){const indent=line.match(/^\s*/)[0].length;const m=line.trim().match(/^([^:]+):\s*(.*)$/);if(!m)throw Error(`Unsupported YAML line: ${line.trim()}`);while(stack.length&&indent<=stack[stack.length-1].indent)stack.pop();const obj=stack[stack.length-1].obj;let v=m[2];if(v==='')v={};else if(v==='true'||v==='false')v=v==='true';else if(v==='null')v=null;else if(/^[-+]?\d+(\.\d+)?$/.test(v))v=Number(v);else if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);obj[m[1].trim()]=v;if(v&&typeof v==='object')stack.push({indent,obj:v})}return root}
function prettyXml(x){const doc=new DOMParser().parseFromString(x,'application/xml');if(doc.querySelector('parsererror'))throw Error('Invalid XML');const s=new XMLSerializer().serializeToString(doc);let out='',depth=0;for(const token of s.replace(/>\s*</g,'><').replace(/></g,'>\n<').split('\n')){if(/^<\//.test(token))depth--;out+='  '.repeat(Math.max(0,depth))+token+'\n';if(/^<[^!?/][^>]*[^/]>(?!.*<\/)/.test(token)&&!/<[^>]+>.*<\//.test(token))depth++}return out.trim()}
function csvParse(s){const rows=[];let row=[],cell='',q=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&s[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(x=>x!==''))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(x=>x!==''))rows.push(row);return rows}
function csvString(rows){return rows.map(r=>r.map(v=>{v=String(v??'');return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}).join(',')).join('\n')}
function simpleFormatCode(s,lang){let x=s.trim();if(lang==='json')return formatJson(x,2);x=x.replace(/\s*\{\s*/g,' {\n').replace(/\s*\}\s*/g,'\n}\n').replace(/;\s*/g,';\n').replace(/,\s*/g,', ');let d=0;return x.split('\n').map(line=>{line=line.trim();if(line.startsWith('}'))d--;const r='  '.repeat(Math.max(0,d))+line;if(line.endsWith('{'))d++;return r}).filter(Boolean).join('\n')}
function simpleMinify(s,lang){if(lang==='json')return JSON.stringify(JSON.parse(s));return s.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/.*$/gm,'').replace(/\s+/g,' ').replace(/\s*([{}();,:])\s*/g,'$1').trim()}
function markdown(s){return esc(s).replace(/^###### (.*)$/gm,'<h6>$1</h6>').replace(/^##### (.*)$/gm,'<h5>$1</h5>').replace(/^#### (.*)$/gm,'<h4>$1</h4>').replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/^[-*] (.*)$/gm,'<li>$1</li>').replace(/\n{2,}/g,'<br><br>').replace(/\n/g,'<br>')}
function diffLines(a,b){const A=a.split(/\r?\n/),B=b.split(/\r?\n/);const n=A.length,m=B.length,dp=Array.from({length:n+1},()=>Array(m+1).fill(0));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i][j]=A[i]===B[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,out=[];while(i<n&&j<m){if(A[i]===B[j]){out.push('  '+esc(A[i]));i++;j++}else if(dp[i+1][j]>=dp[i][j+1]){out.push(`<span class="dev-del">- ${esc(A[i])}</span>`);i++}else{out.push(`<span class="dev-add">+ ${esc(B[j])}</span>`);j++}}while(i<n)out.push(`<span class="dev-del">- ${esc(A[i++])}</span>`);while(j<m)out.push(`<span class="dev-add">+ ${esc(B[j++])}</span>`);return out.join('\n')}
function cryptoRandom(n){const a=new Uint8Array(n);crypto.getRandomValues(a);return a}
function uuid(){const a=cryptoRandom(16);a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;const h=[...a].map(x=>x.toString(16).padStart(2,'0'));return `${h.slice(0,4).join('')}-${h.slice(4,6).join('')}-${h.slice(6,8).join('')}-${h.slice(8,10).join('')}-${h.slice(10).join('')}`}
function ulid(){const alphabet='0123456789ABCDEFGHJKMNPQRSTVWXYZ';let time=Date.now(),t='';for(let i=9;i>=0;i--){t=alphabet[time%32]+t;time=Math.floor(time/32)}let r='';const b=cryptoRandom(16);for(const x of b)r+=alphabet[x%32];return t+r}
function nano(n=21){const chars='useandom-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz';const b=cryptoRandom(n);return [...b].map(x=>chars[x%chars.length]).join('')}
function bytesToHex(b){return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function md5(str){function r(x,n){return(x<<n)|(x>>>(32-n))}function add(a,b){return(a+b)>>>0}const enc=new TextEncoder().encode(str);let a=0x67452301,b=0xefcdab89,c=0x98badcfe,d=0x10325476;const len=((enc.length+8+63)>>6)<<4;const m=new Uint32Array(len);for(let i=0;i<enc.length;i++)m[i>>2]|=enc[i]<<((i%4)*8);m[enc.length>>2]|=0x80<<((enc.length%4)*8);m[len-2]=enc.length*8;const K=[...Array(64)].map((_,i)=>Math.floor(Math.abs(Math.sin(i+1))*2**32)>>>0);const S=[7,12,17,22,5,9,14,20,4,11,16,23,6,10,15,21];for(let i=0;i<len;i+=16){let A=a,B=b,C=c,D=d;for(let j=0;j<64;j++){let F,g;if(j<16){F=(B&C)|((~B)&D);g=j}else if(j<32){F=(D&B)|((~D)&C);g=(5*j+1)%16}else if(j<48){F=B^C^D;g=(3*j+5)%16}else{F=C^(B|(~D));g=(7*j)%16}const q=add(add(add(A,F),K[j]),m[i+g]);const st=S[(j>>4)*4+(j%4)];A=D;D=C;C=B;B=add(B,r(q,st))}a=add(a,A);b=add(b,B);c=add(c,C);d=add(d,D)}const out=new Uint8Array(16),v=[a,b,c,d];for(let i=0;i<16;i++)out[i]=(v[i>>2]>>((i%4)*8))&255;return bytesToHex(out)}
async function digest(alg,text){const b=await crypto.subtle.digest(alg,new TextEncoder().encode(text));return bytesToHex(new Uint8Array(b))}
async function hmac(alg,key,text){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(key),{name:'HMAC',hash:alg},false,['sign']);const b=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(text));return bytesToHex(new Uint8Array(b))}
function mountTextTransform(root,t,fn,title,desc){root.innerHTML=shell(title,desc,twoText('Paste input here…','Your result appears here.'));bindBasic(root,async()=>{try{setOut(root,await fn($(root,'[data-input]').value),true)}catch(e){setOut(root,e.message,false)}})}
function selectTool(root,title,desc,body,run){root.innerHTML=shell(title,desc,body);run&&run();return root}
const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.xml':'application/xml','.txt':'text/plain','.csv':'text/csv','.md':'text/markdown','.svg':'image/svg+xml','.pdf':'application/pdf','.zip':'application/zip','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.mp3':'audio/mpeg','.mp4':'video/mp4','.woff2':'font/woff2'};
function mount(root,t){styles();const id=t.id;
 if(id==='json-formatter'||id==='json-validator'||id==='json-minifier'){const mode=id.split('-')[1];mountTextTransform(root,t,async v=>{if(!v.trim())return '';JSON.parse(v);return mode==='formatter'?formatJson(v,2):mode==='minifier'?formatJson(v,0):'Valid JSON ✓'},t.name,t.description);return}
 if(id==='json-yaml'){root.innerHTML=shell(t.name,t.description,`<div class="dev-toolbar"><button class="primary" id="j2y">JSON → YAML</button><button class="secondary" id="y2j">YAML → JSON</button></div>${twoText('Paste JSON or YAML…')}`);$('#j2y',root).onclick=()=>{try{setOut(root,simpleYaml(JSON.parse($(root,'[data-input]').value)),true)}catch(e){setOut(root,e.message,false)}};$('#y2j',root).onclick=()=>{try{setOut(root,JSON.stringify(yamlToJson($(root,'[data-input]').value),null,2),true)}catch(e){setOut(root,e.message,false)}};$('#clear',root)?.addEventListener('click',()=>{});return}
 if(id==='yaml-formatter'){mountTextTransform(root,t,v=>simpleYaml(yamlToJson(v)),t.name,t.description);return}
 if(id==='xml-formatter'||id==='xml-validator'){mountTextTransform(root,t,v=>{const d=new DOMParser().parseFromString(v,'application/xml');if(d.querySelector('parsererror'))throw Error('Invalid XML');return id==='xml-validator'?'Valid XML ✓':prettyXml(v)},t.name,t.description);return}
 if(id==='csv-json'){root.innerHTML=shell(t.name,t.description,`<div class="dev-toolbar"><button class="primary" id="c2j">CSV → JSON</button><button class="secondary" id="j2c">JSON → CSV</button></div>${twoText('Paste CSV or JSON…')}`);$('#c2j',root).onclick=()=>{try{const r=csvParse($(root,'[data-input]').value);const h=r.shift()||[];setOut(root,JSON.stringify(r.map(row=>Object.fromEntries(h.map((k,i)=>[k,row[i]??'']))),null,2))}catch(e){setOut(root,e.message,false)}};$('#j2c',root).onclick=()=>{try{const a=JSON.parse($(root,'[data-input]').value);if(!Array.isArray(a))throw Error('Expected a JSON array');const h=[...new Set(a.flatMap(o=>Object.keys(o)))];setOut(root,csvString([h,...a.map(o=>h.map(k=>o[k]??''))]))}catch(e){setOut(root,e.message,false)}};return}
 if(id==='toml-formatter'){mountTextTransform(root,t,v=>v.split(/\r?\n/).map(x=>x.trim().replace(/\s*=\s*/,' = ')).join('\n'),t.name,t.description);return}
 if(id==='base64'){root.innerHTML=shell(t.name,t.description,`<div class="dev-toolbar"><button class="primary" id="enc">Encode</button><button class="secondary" id="dec">Decode</button></div>${twoText('Text or Base64…')}`);$('#enc',root).onclick=()=>setOut(root,btoa(unescape(encodeURIComponent($(root,'[data-input]').value))));$('#dec',root).onclick=()=>{try{setOut(root,decodeURIComponent(escape(atob($(root,'[data-input]').value.trim()))))}catch(e){setOut(root,'Invalid Base64',false)}};return}
 if(id==='url-encoder'){root.innerHTML=shell(t.name,t.description,`<div class="dev-toolbar"><button class="primary" id="enc">Encode</button><button class="secondary" id="dec">Decode</button></div>${twoText('Text or URL…')}`);$('#enc',root).onclick=()=>setOut(root,encodeURIComponent($(root,'[data-input]').value));$('#dec',root).onclick=()=>{try{setOut(root,decodeURIComponent($(root,'[data-input]').value))}catch(e){setOut(root,e.message,false)}};return}
 if(id==='html-entities'){root.innerHTML=shell(t.name,t.description,`<div class="dev-toolbar"><button class="primary" id="enc">Encode</button><button class="secondary" id="dec">Decode</button></div>${twoText('Text or HTML entities…')}`);$('#enc',root).onclick=()=>setOut(root,esc($(root,'[data-input]').value));$('#dec',root).onclick=()=>{const ta=document.createElement('textarea');ta.innerHTML=$(root,'[data-input]').value;setOut(root,ta.value)};return}
 if(id==='unicode'){mountTextTransform(root,t,v=>[...v].map(c=>`U+${c.codePointAt(0).toString(16).toUpperCase().padStart(4,'0')} ${c}`).join('\n'),t.name,t.description);return}
 if(id==='hex'){root.innerHTML=shell(t.name,t.description,`<div class="dev-toolbar"><button class="primary" id="enc">Text → Hex</button><button class="secondary" id="dec">Hex → Text</button></div>${twoText('Paste text or hex…')}`);$('#enc',root).onclick=()=>setOut(root,bytesToHex(new TextEncoder().encode($(root,'[data-input]').value)));$('#dec',root).onclick=()=>{try{const h=$(root,'[data-input]').value.replace(/\s+/g,'');if(!/^[0-9a-f]*$/i.test(h)||h.length%2)throw Error('Invalid hexadecimal');setOut(root,new TextDecoder().decode(Uint8Array.from(h.match(/../g)||[],x=>parseInt(x,16))))}catch(e){setOut(root,e.message,false)}};return}
 if(id==='binary'){root.innerHTML=shell(t.name,t.description,`<div class="dev-toolbar"><button class="primary" id="enc">Text → Binary</button><button class="secondary" id="dec">Binary → Text</button></div>${twoText('Paste text or binary…')}`);$('#enc',root).onclick=()=>setOut(root,[...new TextEncoder().encode($(root,'[data-input]').value)].map(x=>x.toString(2).padStart(8,'0')).join(' '));$('#dec',root).onclick=()=>{try{setOut(root,new TextDecoder().decode(Uint8Array.from($(root,'[data-input]').value.trim().split(/\s+/),x=>parseInt(x,2))))}catch(e){setOut(root,'Invalid binary',false)}};return}
 if(id==='url-parser'){root.innerHTML=shell(t.name,t.description,`<div class="dev-row"><input class="dev-input" id="url" placeholder="https://example.com/path?q=1#section"><button class="primary" id="parse">Parse</button></div><div class="dev-result-grid" id="result" style="margin-top:14px"></div>`);$('#parse',root).onclick=()=>{try{const u=new URL($('#url',root).value);const vals={protocol:u.protocol,username:u.username,host:u.host,hostname:u.hostname,port:u.port||'(default)',pathname:u.pathname,search:u.search||'',hash:u.hash||''};$('#result',root).innerHTML=Object.entries(vals).map(([k,v])=>`<div class="dev-result"><div class="dev-label">${esc(k)}</div><div class="dev-code">${esc(v)}</div></div>`).join('')}catch(e){$('#result',root).innerHTML=`<p class="dev-error">${esc(e.message)}</p>`}};return}
 if(id==='query-parser'){mountTextTransform(root,t,v=>{const u=new URL(v.includes('?')?v:'https://toolzy.local/?'+v);return [...u.searchParams.entries()].map(([k,val])=>`${k} = ${val}`).join('\n')},t.name,t.description);return}
 if(id==='jwt-decoder'){mountTextTransform(root,t,v=>{const p=v.split('.');if(p.length!==3)throw Error('A JWT must have 3 parts');const dec=x=>JSON.stringify(JSON.parse(decodeURIComponent(escape(atob(x.replace(/-/g,'+').replace(/_/g,'/'))))),null,2);return `HEADER\n${dec(p[0])}\n\nPAYLOAD\n${dec(p[1])}\n\nSignature is not verified locally.`},t.name,t.description);return}
 if(id==='http-status'){const statuses={100:'Continue',101:'Switching Protocols',200:'OK',201:'Created',202:'Accepted',204:'No Content',301:'Moved Permanently',302:'Found',304:'Not Modified',400:'Bad Request',401:'Unauthorized',403:'Forbidden',404:'Not Found',405:'Method Not Allowed',408:'Request Timeout',409:'Conflict',410:'Gone',413:'Content Too Large',415:'Unsupported Media Type',422:'Unprocessable Content',429:'Too Many Requests',500:'Internal Server Error',501:'Not Implemented',502:'Bad Gateway',503:'Service Unavailable',504:'Gateway Timeout'};root.innerHTML=shell(t.name,t.description,`<input class="dev-input" id="q" placeholder="Search status code or name…"><div id="list" class="dev-result-grid" style="margin-top:14px"></div>`);const render=()=>{const q=$('#q',root).value.toLowerCase();$('#list',root).innerHTML=Object.entries(statuses).filter(([c,n])=>(c+' '+n).toLowerCase().includes(q)).map(([c,n])=>`<div class="dev-result"><div class="dev-stat">${c}</div><div>${n}</div></div>`).join('')||'<p class="dev-muted">No matching status.</p>'};$('#q',root).oninput=render;render();return}
 if(id==='http-headers'){mountTextTransform(root,t,v=>{const o={};v.split(/\r?\n/).forEach(l=>{const i=l.indexOf(':');if(i>0)o[l.slice(0,i).trim()]=l.slice(i+1).trim()});return JSON.stringify(o,null,2)},t.name,t.description);return}
 if(id==='user-agent'){mountTextTransform(root,t,v=>{const isChrome=/Chrome\//.test(v)&&!/Edg\//.test(v),isFirefox=/Firefox\//.test(v),isSafari=/Safari\//.test(v)&&!/Chrome\//.test(v),isEdge=/Edg\//.test(v);return JSON.stringify({browser:isEdge?'Microsoft Edge':isChrome?'Google Chrome':isFirefox?'Mozilla Firefox':isSafari?'Safari':'Unknown',mobile:/Mobile|Android|iPhone|iPad/i.test(v),platform:/Windows/.test(v)?'Windows':/Mac OS/.test(v)?'macOS':/Android/.test(v)?'Android':/iPhone|iPad/.test(v)?'iOS':/Linux/.test(v)?'Linux':'Unknown'},null,2)},t.name,t.description);return}
 if(id==='mime-types'){root.innerHTML=shell(t.name,t.description,`<div class="dev-row"><input class="dev-input" id="q" placeholder=".json or application/json"><button class="primary" id="find">Find</button></div><div id="out" class="dev-output" style="margin-top:14px"></div>`);$('#find',root).onclick=()=>{const q=$('#q',root).value.trim().toLowerCase();const r=q.startsWith('.')?mime[q]:Object.entries(mime).find(([,v])=>v===q)?.[0];$('#out',root).textContent=r?`${q.startsWith('.')?r:q+' → '+r}`:'No common match found.'};return}
 if(id==='color-converter'){root.innerHTML=shell(t.name,t.description,`<div class="dev-row"><input class="dev-input" id="c" value="#6750A4"><button class="primary" id="go">Convert</button></div><div id="out" class="dev-result-grid" style="margin-top:14px"></div>`);$('#go',root).onclick=()=>{let x=$('#c',root).value.trim(),r;if(/^#[0-9a-f]{6}$/i.test(x)){const n=parseInt(x.slice(1),16);r={hex:x.toUpperCase(),rgb:`rgb(${n>>16}, ${(n>>8)&255}, ${n&255})`}}else{const m=x.match(/rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/i);if(!m)return;const [R,G,B]=m.slice(1).map(Number),h=Math.max(R,G,B),l=Math.min(R,G,B),d=h-l;let H=0,S=0;const L=(h+l)/510;if(d){S=d/(255-Math.abs(2*L-1)*255);if(h===R)H=60*(((G-B)/d)%6);else if(h===G)H=60*((B-R)/d+2);else H=60*((R-G)/d+4);if(H<0)H+=360}r={rgb:`rgb(${R}, ${G}, ${B})`,hsl:`hsl(${Math.round(H)}, ${Math.round(S*100)}%, ${Math.round(L*100)}%)`}}$('#out',root).innerHTML=Object.entries(r).map(([k,v])=>`<div class="dev-result"><div class="dev-label">${k}</div><div class="dev-code">${v}</div></div>`).join('')};return}
 if(id==='markdown-editor'){root.innerHTML=shell(t.name,t.description,`<div class="dev-grid2"><textarea class="dev-editor" id="md" placeholder="# Hello\n\nWrite **Markdown** here…"></textarea><div class="dev-preview" id="preview"></div></div>`);const update=()=>$('#preview',root).innerHTML=markdown($('#md',root).value);$('#md',root).oninput=update;update();return}
 if(['html-formatter','css-formatter','javascript-formatter','sql-formatter','javascript-minifier','sql-minifier'].includes(id)){const lang=id.includes('html')?'html':id.includes('css')?'css':id.includes('javascript')?'js':'sql';const mini=id.includes('minifier');mountTextTransform(root,t,v=>mini?simpleMinify(v,lang):simpleFormatCode(v,lang),t.name,t.description);return}
 if(id==='code-diff'||id==='text-diff'){root.innerHTML=shell(t.name,t.description,`<div class="dev-grid2"><textarea class="dev-editor" id="a" placeholder="Original…"></textarea><textarea class="dev-editor" id="b" placeholder="Modified…"></textarea></div><div class="dev-toolbar"><button class="primary" id="run">Compare</button><button class="secondary" id="copy">Copy</button></div><div class="dev-output dev-diff" id="out"></div>`);$('#run',root).onclick=()=>$('#out',root).innerHTML=diffLines($('#a',root).value,$('#b',root).value);$('#copy',root).onclick=()=>copy($('#out',root).innerText);return}
 if(id==='regex-tester'){root.innerHTML=shell(t.name,t.description,`<div class="dev-grid2"><div><input class="dev-input" id="rx" value="\\b[A-Z][a-z]+\\b" placeholder="Pattern"><input class="dev-input" id="flags" value="g" style="margin-top:10px" placeholder="Flags"><textarea class="dev-editor" id="txt" style="margin-top:10px" placeholder="Sample text…"></textarea></div><pre class="dev-output" id="out">Matches appear here.</pre></div><div class="dev-toolbar"><button class="primary" id="run">Test</button></div>`);$('#run',root).onclick=()=>{try{const re=new RegExp($('#rx',root).value,$('#flags',root).value);const m=[...$('#txt',root).value.matchAll(re)];$('#out',root).textContent=`${m.length} match${m.length===1?'':'es'}\n\n`+m.map((x,i)=>`${i+1}. ${x[0]} @ ${x.index}`).join('\n')}catch(e){$('#out',root).textContent=e.message}};return}
 if(['uuid','ulid','nanoid','random-string'].includes(id)){root.innerHTML=shell(t.name,t.description,`<div class="dev-row"><input class="dev-input" id="count" type="number" value="5" min="1" max="100"><input class="dev-input" id="length" type="number" value="21" min="4" max="128"><button class="primary" id="gen">Generate</button></div><pre class="dev-output" id="out" style="margin-top:14px"></pre>`);$('#gen',root).onclick=()=>{const n=Math.min(100,Math.max(1,+$('#count',root).value||1)),len=Math.min(128,Math.max(4,+$('#length',root).value||21));let arr=Array.from({length:n},()=>id==='uuid'?uuid():id==='ulid'?ulid():id==='nanoid'?nano(len):[...cryptoRandom(len)].map(x=>'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-'.charAt(x%64)).join(''));$('#out',root).textContent=arr.join('\n')};$('#gen',root).click();return}
 if(id==='test-data'){root.innerHTML=shell(t.name,t.description,`<div class="dev-row"><input class="dev-input" id="count" type="number" value="10" min="1" max="100"><select class="dev-input dev-select" id="format"><option value="json">JSON</option><option value="csv">CSV</option></select><button class="primary" id="gen">Generate</button></div><pre class="dev-output" id="out" style="margin-top:14px"></pre>`);$('#gen',root).onclick=()=>{const n=Math.min(100,Math.max(1,+$('#count',root).value||10)),a=Array.from({length:n},(_,i)=>({id:i+1,name:['Aarav','Mira','Riya','Kabir','Ishaan'][i%5]+' '+['Patil','Sharma','Mehta','Khan'][i%4],email:`user${i+1}@example.com`,active:i%2===0}));$('#out',root).textContent=$('#format',root).value==='json'?JSON.stringify(a,null,2):csvString([Object.keys(a[0]),...a.map(o=>Object.values(o))])};$('#gen',root).click();return}
 if(['unix-timestamp','iso-date','date-timestamp'].includes(id)){root.innerHTML=shell(t.name,t.description,`<div class="dev-row"><input class="dev-input" id="v" placeholder="Timestamp, ISO date, or date/time"><button class="primary" id="go">Convert</button></div><div class="dev-output" id="out" style="margin-top:14px"></div>`);$('#go',root).onclick=()=>{const v=$('#v',root).value.trim();let d;if(id==='unix-timestamp'){const ms=/^\d+$/.test(v)?(+v<1e12?+v*1000:+v):Date.parse(v);if(!Number.isFinite(ms))return $('#out',root).textContent='Invalid timestamp';d=new Date(ms)}else if(id==='iso-date'){d=new Date(v);if(isNaN(d))return $('#out',root).textContent='Invalid date'}else{d=new Date(v);if(isNaN(d))return $('#out',root).textContent='Invalid date'}$('#out',root).textContent=`ISO 8601\n${d.toISOString()}\n\nUnix seconds\n${Math.floor(d.getTime()/1000)}\n\nUnix milliseconds\n${d.getTime()}`};return}
 if(id==='cron-helper'){root.innerHTML=shell(t.name,t.description,`<input class="dev-input" id="cron" value="*/5 * * * *"><div class="dev-result-grid" id="out" style="margin-top:14px"></div>`);$('#cron',root).oninput=()=>{const p=$('#cron',root).value.trim().split(/\s+/);const names=['Minute','Hour','Day of month','Month','Day of week'];$('#out',root).innerHTML=(p.length===5?p.map((x,i)=>`<div class="dev-result"><div class="dev-label">${names[i]}</div><div class="dev-code">${esc(x)}</div></div>`):['<p class="dev-error">Use five cron fields.</p>']).join('')};$('#cron',root).dispatchEvent(new Event('input'));return}
 if(id==='hash-generator'||id==='checksum'){root.innerHTML=shell(t.name,t.description,`<select class="dev-input dev-select" id="alg"><option>MD5</option><option>SHA-1</option><option>SHA-256</option><option>SHA-512</option></select><textarea class="dev-editor" id="txt" placeholder="Text to hash…" style="margin-top:10px;min-height:180px"></textarea><div class="dev-toolbar"><button class="primary" id="go">Generate hash</button><button class="secondary" id="copy">Copy</button></div><pre class="dev-output" id="out"></pre>`);$('#go',root).onclick=async()=>{const a=$('#alg',root).value,v=$('#txt',root).value;try{const h=a==='MD5'?md5(v):await digest(a,v);$('#out',root).textContent=h}catch(e){$('#out',root).textContent=e.message}};$('#copy',root).onclick=()=>copy($('#out',root).textContent);return}
 if(id==='hmac-generator'){root.innerHTML=shell(t.name,t.description,`<select class="dev-input dev-select" id="alg"><option value="SHA-256">HMAC-SHA-256</option><option value="SHA-1">HMAC-SHA-1</option><option value="SHA-512">HMAC-SHA-512</option></select><input class="dev-input" id="key" placeholder="Secret key" style="margin-top:10px"><textarea class="dev-editor" id="txt" placeholder="Message…" style="margin-top:10px;min-height:180px"></textarea><button class="primary" id="go">Generate HMAC</button><pre class="dev-output" id="out"></pre>`);$('#go',root).onclick=async()=>{try{$('#out',root).textContent=await hmac($('#alg',root).value,$('#key',root).value,$('#txt',root).value)}catch(e){$('#out',root).textContent=e.message}};return}
}
export {mount};
