// Toolzy — Google Material Symbols Rounded
const aliases = {
  home:"home",
  build:"build",
  gear:"settings",
  settings:"settings",
  text:"text_fields",
  calculator:"calculate",
  show_chart:"show_chart",
  currency_exchange:"currency_exchange",
  show_chart:"show_chart",
  percent:"percent",
  swap:"swap_horiz",
  code:"code",
  image:"image",
  pdf:"picture_as_pdf",
  folder:"folder",
  folder_open:"folder_open",
  picture_as_pdf:"picture_as_pdf",
  "sparkle-star":"auto_awesome",
  sparkle:"auto_awesome",
  extension:"extension",
  lock:"lock",
  search:"search",
  back:"arrow_back",
  "arrow-left":"arrow_back",
  arrow:"arrow_forward",
  "arrow-right":"arrow_forward",
  percent:"percent",
  calendar:"calendar_month",
  clock:"schedule",
  star:"star",
  check:"check",
  close:"close",
  download:"download",
  upload:"upload",
  copy:"content_copy",
  refresh:"refresh",
  pencil:"edit",
  edit:"edit",
  dice:"casino",
  robot:"smart_toy",
  palette:"palette",
  scroll:"article",
  package:"inventory_2",
  "shield-cross":"shield",
  shield:"shield",
  at:"alternate_email",
  link:"link",
  broom:"cleaning_services",
  id:"badge",
  trash:"delete",
  menu:"menu",
  dark_mode:"dark_mode",
  light_mode:"light_mode",
  "data-object":"account_tree",
  "code-block":"integration_instructions",
  compare:"compare",
  compress:"compress",
  info:"info",
  file:"insert_drive_file",
  language:"language",
  key:"key",
  table:"table_view",
  schedule:"schedule",
  shuffle:"shuffle",
  "123":"123",
  "handyman":"handyman",
  "savings":"savings",
  "devices":"devices",
  "sports_esports":"sports_esports",
  "fingerprint":"fingerprint",
  "public":"public",
  "policy":"policy",
  "checklist":"checklist",
  "date_range":"date_range",
  "timer":"schedule",
  "calendar_month":"calendar_month",
  "work_history":"work_history",
  "view_week":"view_week",
  "auto_awesome":"auto_awesome",
  "toll":"toll",
  "casino":"casino",
  "password":"password",
  "groups":"groups",
  "receipt_long":"receipt_long",
  "volunteer_activism":"favorite",
  "account_balance_wallet":"account_balance_wallet",
  "local_gas_station":"local_gas_station",
  "school":"school",
  "aspect_ratio":"aspect_ratio",
  "wifi":"wifi",
  "monitor":"monitor",
  "keyboard":"keyboard",
  "fullscreen":"fullscreen",
  "gradient":"gradient",
  "emoji_emotions":"emoji_emotions",
  "volume_up":"volume_up",
  "swap_vert":"swap_vert",
  "bolt":"flash_on",
  "leaderboard":"bar_chart",
  "favorite":"favorite",
  "psychology":"auto_awesome",
  "vpn_key":"vpn_key",
  "dialpad":"dialpad",
  "confirmation_number":"confirmation_number",
  "security":"security",
  "verified":"verified",
  "description":"description",
  "http":"http",
  "cookie":"cookie",
  "share":"share",
  "tune":"tune",
  "manage_search":"manage_search",
  "pattern":"pattern",
  "database":"database",
};

function esc(value){
  return String(value ?? "").replace(/[&<>"']/g, c => ({
    "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"
  }[c]));
}

export function icon(name,label=""){
  const glyph = aliases[name] || "extension";
  const aria = label
    ? ` aria-label="${esc(label)}" role="img"`
    : ' aria-hidden="true"';
  return `<span class="material-symbols-rounded"${aria}>${esc(glyph)}</span>`;
}

export function art(name,label="",extra=""){
  return `<span class="material-art ${esc(extra)}" aria-hidden="true">${icon(name,label)}</span>`;
}
