export const categories = [
  { id:"basic", name:"Basic", icon:"build", description:"Everyday quick tools, made fast" },
  { id:"text", name:"Text", icon:"text", description:"Write, clean & transform text" },
  { id:"calculators", name:"Calculators", icon:"calculator", description:"Math and everyday calculations" },
  { id:"converters", name:"Converters", icon:"swap", description:"Convert units and formats" },
  { id:"developer", name:"Developer", icon:"code", description:"Tools for code, data and web work", subcategories:[
    {id:"data",name:"Data & Serialization",icon:"data-object"},
    {id:"encoding",name:"Encoding & Decoding",icon:"code"},
    {id:"web",name:"Web",icon:"language"},
    {id:"code",name:"Code",icon:"code-block"},
    {id:"identifiers",name:"Identifiers & Data",icon:"id"},
    {id:"time",name:"Time",icon:"clock"},
    {id:"hashing",name:"Hashing & Checksums",icon:"key"}
  ] },
  { id:"utilities", name:"Utilities", icon:"handyman", description:"Fun, practical and browser-native tools", subcategories:[
    {id:"time",name:"Date & Time",icon:"schedule"},
    {id:"random",name:"Random & Generators",icon:"shuffle"},
    {id:"planning",name:"Money & Planning",icon:"savings"},
    {id:"browser",name:"Browser & Device",icon:"devices"},
    {id:"creative",name:"Creative & Voice",icon:"palette"},
    {id:"games",name:"Games & Fun",icon:"sports_esports"}
  ] },
  { id:"security", name:"Security", icon:"lock", description:"Defensive security, privacy and integrity tools", subcategories:[
    {id:"access",name:"Passwords & Access",icon:"key"},
    {id:"integrity",name:"Integrity & Hashing",icon:"fingerprint"},
    {id:"web",name:"Web Security",icon:"public"},
    {id:"inspection",name:"Inspection & Privacy",icon:"policy"},
    {id:"habits",name:"Security Habits",icon:"checklist"}
  ] },
  { id:"pdf", name:"PDF Editor", icon:"picture_as_pdf", description:"View, edit and organize PDF documents", kind:"product" }
];


export const tools = [
  {id:"world-clock", category:"utilities", subcategory:"time", name:"World Clock", icon:"schedule", description:"Live clocks for popular cities with automatic updates.", module:"../tools/utilities/world-clock.js"},
  {id:"timezone-converter", category:"utilities", subcategory:"time", name:"Time Zone Converter", icon:"public", description:"Convert a date and time between common time zones.", module:"../tools/utilities/timezone-converter.js"},
  {id:"date-difference", category:"utilities", subcategory:"time", name:"Date Difference", icon:"date_range", description:"Measure the span between two dates.", module:"../tools/utilities/date-difference.js"},
  {id:"countdown", category:"utilities", subcategory:"time", name:"Countdown Timer", icon:"timer", description:"Run a live countdown to any date and time.", module:"../tools/utilities/countdown.js"},
  {id:"pomodoro", category:"utilities", subcategory:"time", name:"Pomodoro Timer", icon:"timer", description:"Focus and break cycles with a session counter.", module:"../tools/utilities/pomodoro.js"},
  {id:"calendar-generator", category:"utilities", subcategory:"time", name:"Calendar Generator", icon:"calendar_month", description:"Generate a clean month calendar for any year.", module:"../tools/utilities/calendar-generator.js"},
  {id:"business-days", category:"utilities", subcategory:"time", name:"Business Days Calculator", icon:"work_history", description:"Count weekdays between two dates.", module:"../tools/utilities/business-days.js"},
  {id:"week-number", category:"utilities", subcategory:"time", name:"Week Number", icon:"view_week", description:"Get ISO week and day-of-year information.", module:"../tools/utilities/week-number.js"},
  {id:"shuffle-list", category:"utilities", subcategory:"random", name:"Shuffle List", icon:"shuffle", description:"Randomize a list while keeping every item.", module:"../tools/utilities/shuffle-list.js"},
  {id:"fortune-generator", category:"utilities", subcategory:"random", name:"Fortune Generator", icon:"auto_awesome", description:"Reveal a playful random answer to a question.", module:"../tools/utilities/fortune-generator.js"},
  {id:"coin-flip", category:"utilities", subcategory:"random", name:"Coin Flip", icon:"toll", description:"Flip one coin or run a batch of flips.", module:"../tools/utilities/coin-flip.js"},
  {id:"spin-wheel", category:"utilities", subcategory:"random", name:"Spin the Wheel", icon:"casino", description:"Spin a colorful wheel to choose one option.", module:"../tools/utilities/spin-wheel.js"},
  {id:"password-generator", category:"utilities", subcategory:"random", name:"Password Generator", icon:"password", description:"Generate strong local passwords with configurable character sets.", module:"../tools/utilities/password-generator.js"},
  {id:"random-color", category:"utilities", subcategory:"random", name:"Random Color", icon:"palette", description:"Generate and copy random HEX colors.", module:"../tools/utilities/random-color.js"},
  {id:"random-teams", category:"utilities", subcategory:"random", name:"Random Team Generator", icon:"groups", description:"Shuffle people into balanced teams.", module:"../tools/utilities/random-teams.js"},
  {id:"number-sequence", category:"utilities", subcategory:"random", name:"Number Sequence Generator", icon:"123", description:"Create arithmetic or geometric number sequences.", module:"../tools/utilities/number-sequence.js"},
  {id:"split-bill", category:"utilities", subcategory:"planning", name:"Split Bill", icon:"receipt_long", description:"Split a bill with people and tip included.", module:"../tools/utilities/split-bill.js"},
  {id:"tip-planner", category:"utilities", subcategory:"planning", name:"Tip Planner", icon:"volunteer_activism", description:"Compare common tip percentages at a glance.", module:"../tools/utilities/tip-planner.js"},
  {id:"discount-breakdown", category:"utilities", subcategory:"planning", name:"Discount Breakdown", icon:"percent", description:"See savings, discounted price and optional tax.", module:"../tools/utilities/discount-breakdown.js"},
  {id:"savings-goal", category:"utilities", subcategory:"planning", name:"Savings Goal", icon:"savings", description:"Calculate the monthly amount needed for a target.", module:"../tools/utilities/savings-goal.js"},
  {id:"budget-split", category:"utilities", subcategory:"planning", name:"Budget Split", icon:"account_balance_wallet", description:"Split a budget into practical buckets.", module:"../tools/utilities/budget-split.js"},
  {id:"fuel-cost", category:"utilities", subcategory:"planning", name:"Fuel Cost", icon:"local_gas_station", description:"Estimate fuel usage and trip cost.", module:"../tools/utilities/fuel-cost.js"},
  {id:"grade-tracker", category:"utilities", subcategory:"planning", name:"Grade Tracker", icon:"school", description:"Calculate weighted marks from assessments.", module:"../tools/utilities/grade-tracker.js"},
  {id:"aspect-ratio", category:"utilities", subcategory:"planning", name:"Aspect Ratio Helper", icon:"aspect_ratio", description:"Reduce dimensions and calculate matching sizes.", module:"../tools/utilities/aspect-ratio.js"},
  {id:"browser-info", category:"utilities", subcategory:"browser", name:"Browser Info", icon:"language", description:"Inspect browser-provided session information.", module:"../tools/utilities/browser-info.js"},
  {id:"device-info", category:"utilities", subcategory:"browser", name:"Device Info", icon:"devices", description:"Inspect viewport, screen, touch and pixel details.", module:"../tools/utilities/device-info.js"},
  {id:"network-status", category:"utilities", subcategory:"browser", name:"Network Status", icon:"wifi", description:"Inspect online state and connection hints.", module:"../tools/utilities/network-status.js"},
  {id:"screen-info", category:"utilities", subcategory:"browser", name:"Screen Info", icon:"monitor", description:"Inspect display size, orientation and pixel ratio.", module:"../tools/utilities/screen-info.js"},
  {id:"keyboard-tester", category:"utilities", subcategory:"browser", name:"Keyboard Tester", icon:"keyboard", description:"Test keys, codes, modifiers and recent presses.", module:"../tools/utilities/keyboard-tester.js"},
  {id:"fullscreen-tester", category:"utilities", subcategory:"browser", name:"Fullscreen Tester", icon:"fullscreen", description:"Test browser fullscreen support.", module:"../tools/utilities/fullscreen-tester.js"},
  {id:"url-inspector", category:"utilities", subcategory:"browser", name:"URL Inspector", icon:"link", description:"Break a URL into its useful parts.", module:"../tools/utilities/url-inspector.js"},
  {id:"color-palette", category:"utilities", subcategory:"creative", name:"Color Palette", icon:"palette", description:"Build a light-to-dark palette from a base color.", module:"../tools/utilities/color-palette.js"},
  {id:"gradient-generator", category:"utilities", subcategory:"creative", name:"Gradient Generator", icon:"gradient", description:"Create and copy ready-to-use CSS gradients.", module:"../tools/utilities/gradient-generator.js"},
  {id:"emoji-picker", category:"utilities", subcategory:"creative", name:"Emoji Picker", icon:"emoji_emotions", description:"Browse and copy handy emojis quickly.", module:"../tools/utilities/emoji-picker.js"},
  {id:"text-to-speech", category:"utilities", subcategory:"creative", name:"Text to Speech", icon:"volume_up", description:"Read text aloud using the browser voice engine.", module:"../tools/utilities/text-to-speech.js"},
  {id:"higher-lower", category:"utilities", subcategory:"games", name:"Higher or Lower", icon:"swap_vert", description:"Predict whether the next number will be higher or lower.", module:"../tools/utilities/higher-lower.js"},
  {id:"reaction-timer", category:"utilities", subcategory:"games", name:"Reaction Timer", icon:"bolt", description:"Measure how quickly you react to the signal.", module:"../tools/utilities/reaction-timer.js"},
  {id:"scoreboard", category:"utilities", subcategory:"games", name:"Scoreboard", icon:"leaderboard", description:"Touch-friendly scoring for games, quizzes and practice.", module:"../tools/utilities/scoreboard.js"},
  {id:"typing-speed", category:"utilities", subcategory:"games", name:"Typing Speed", icon:"keyboard", description:"Measure WPM and typing accuracy in a 30-second test.", module:"../tools/utilities/typing-speed.js"},
  {id:"simple-interest", category:"calculators", name:"Simple Interest Calculator", icon:"percent", description:"Calculate simple interest and total amount.", module:"../tools/calculators/simple-interest.js"},
  {id:"compound-interest", category:"calculators", name:"Compound Interest Calculator", icon:"percent", description:"Calculate compound growth and interest.", module:"../tools/calculators/compound-interest.js"},
  {id:"emi-calculator", category:"calculators", name:"EMI Calculator", icon:"calculator", description:"Calculate monthly loan payments.", module:"../tools/calculators/emi-calculator.js"},
  {id:"loan-payment", category:"calculators", name:"Loan Payment Calculator", icon:"calculator", description:"Calculate periodic loan payments.", module:"../tools/calculators/loan-payment.js"},
  {id:"mean-median-mode", category:"calculators", name:"Mean Median Mode", icon:"calculator", description:"Find mean, median and mode.", module:"../tools/calculators/mean-median-mode.js"},
  {id:"gcd-lcm", category:"calculators", name:"GCD & LCM Calculator", icon:"calculator", description:"Calculate greatest common divisor and least common multiple.", module:"../tools/calculators/gcd-lcm.js"},
  {id:"prime-checker", category:"calculators", name:"Prime Number Checker", icon:"calculator", description:"Check whether an integer is prime.", module:"../tools/calculators/prime-checker.js"},
  {id:"quadratic-solver", category:"calculators", name:"Quadratic Equation Solver", icon:"calculator", description:"Solve quadratic equations.", module:"../tools/calculators/quadratic-solver.js"},
  {id:"pythagorean", category:"calculators", name:"Pythagorean Theorem", icon:"calculator", description:"Calculate a missing right-triangle side.", module:"../tools/calculators/pythagorean.js"},
  {id:"speed-distance-time", category:"calculators", name:"Speed Distance Time", icon:"calculator", description:"Calculate distance from speed and time.", module:"../tools/calculators/speed-distance-time.js"},
  {id:"probability", category:"calculators", name:"Probability Calculator", icon:"calculator", description:"Calculate simple probability.", module:"../tools/calculators/probability.js"},
  {id:"area-volume", category:"calculators", name:"Area & Volume Calculator", icon:"calculator", description:"Calculate common geometric areas and volumes.", module:"../tools/calculators/area-volume.js"},
  {id:"percent-change", category:"calculators", name:"Percent Change Calculator", icon:"percent", description:"Calculate percentage increase or decrease.", module:"../tools/calculators/percent-change.js"},
  {id:"graph-calculator", category:"calculators", name:"Graph Calculator", icon:"show_chart", description:"Plot mathematical functions on a live graph.", module:"../tools/calculators/graph-calculator.js"},
  {id:"length-converter", category:"converters", name:"Length Converter", icon:"swap", description:"Convert common length units.", module:"../tools/converters/length.js"},
  {id:"mass-converter", category:"converters", name:"Mass Converter", icon:"swap", description:"Convert weight and mass units.", module:"../tools/converters/mass.js"},
  {id:"temperature-converter", category:"converters", name:"Temperature Converter", icon:"swap", description:"Convert Celsius, Fahrenheit and Kelvin.", module:"../tools/converters/temperature.js"},
  {id:"area-converter", category:"converters", name:"Area Converter", icon:"swap", description:"Convert common area units.", module:"../tools/converters/area.js"},
  {id:"volume-converter", category:"converters", name:"Volume Converter", icon:"swap", description:"Convert volume and capacity units.", module:"../tools/converters/volume.js"},
  {id:"speed-converter", category:"converters", name:"Speed Converter", icon:"swap", description:"Convert speed units.", module:"../tools/converters/speed.js"},
  {id:"time-converter", category:"converters", name:"Time Converter", icon:"swap", description:"Convert time units.", module:"../tools/converters/time.js"},
  {id:"data-converter", category:"converters", name:"Data Storage Converter", icon:"swap", description:"Convert bytes and binary storage units.", module:"../tools/converters/data.js"},
  {id:"pressure-converter", category:"converters", name:"Pressure Converter", icon:"swap", description:"Convert pressure units.", module:"../tools/converters/pressure.js"},
  {id:"energy-converter", category:"converters", name:"Energy Converter", icon:"swap", description:"Convert energy units.", module:"../tools/converters/energy.js"},
  {id:"power-converter", category:"converters", name:"Power Converter", icon:"swap", description:"Convert power units.", module:"../tools/converters/power.js"},
  {id:"angle-converter", category:"converters", name:"Angle Converter", icon:"swap", description:"Convert degrees, radians, gradians and turns.", module:"../tools/converters/angle.js"},
  {id:"frequency-converter", category:"converters", name:"Frequency Converter", icon:"swap", description:"Convert frequency units.", module:"../tools/converters/frequency.js"},
  {id:"number-base-converter", category:"converters", name:"Number Base Converter", icon:"swap", description:"Convert numbers between bases 2, 8, 10 and 16.", module:"../tools/converters/number-base.js"},
  {id:"currency-converter", category:"converters", name:"Currency Converter", icon:"currency_exchange", description:"Convert currencies using current reference rates.", module:"../tools/converters/currency.js"},
  {id:"password-strength", category:"security", subcategory:"access", name:"Password Strength Checker", icon:"key", description:"Evaluate password strength locally without uploading it.", module:"../tools/security/password-strength.js"},
  {id:"passphrase", category:"security", subcategory:"access", name:"Passphrase Generator", icon:"password", description:"Generate memorable multi-word passphrases locally.", module:"../tools/security/passphrase.js"},
  {id:"secure-token", category:"security", subcategory:"access", name:"Secure Token Generator", icon:"vpn_key", description:"Generate random URL-safe tokens with Web Crypto.", module:"../tools/security/secure-token.js"},
  {id:"pin-strength", category:"security", subcategory:"access", name:"PIN Strength Checker", icon:"dialpad", description:"Spot obvious weak patterns in numeric PINs.", module:"../tools/security/pin-strength.js"},
  {id:"recovery-codes", category:"security", subcategory:"access", name:"Recovery Code Generator", icon:"confirmation_number", description:"Generate backup codes for accounts you control.", module:"../tools/security/recovery-codes.js"},
  {id:"totp-generator", category:"security", subcategory:"access", name:"TOTP Code Generator", icon:"security", description:"Generate a time-based code from a Base32 secret.", module:"../tools/security/totp-generator.js"},
  {id:"sha-hash", category:"security", subcategory:"integrity", name:"SHA Hash Generator", icon:"fingerprint", description:"Calculate SHA-1, SHA-256 or SHA-512 locally.", module:"../tools/security/sha-hash.js"},
  {id:"sri-generator", category:"security", subcategory:"integrity", name:"SRI Hash Generator", icon:"verified", description:"Create a Subresource Integrity hash from asset contents.", module:"../tools/security/sri-generator.js"},
  {id:"file-hash", category:"security", subcategory:"integrity", name:"File Hash Checker", icon:"description", description:"Hash a local file in your browser without uploading it.", module:"../tools/security/file-hash.js"},
  {id:"hash-compare", category:"security", subcategory:"integrity", name:"Hash Compare", icon:"compare", description:"Compare two hexadecimal digests locally.", module:"../tools/security/hash-compare.js"},
  {id:"csp-builder", category:"security", subcategory:"web", name:"CSP Builder", icon:"policy", description:"Build a Content-Security-Policy header from common directives.", module:"../tools/security/csp-builder.js"},
  {id:"security-headers", category:"security", subcategory:"web", name:"Security Headers Analyzer", icon:"http", description:"Inspect pasted response headers for useful protections.", module:"../tools/security/security-headers.js"},
  {id:"cookie-analyzer", category:"security", subcategory:"web", name:"Cookie Security Analyzer", icon:"cookie", description:"Inspect pasted Set-Cookie lines for common flags.", module:"../tools/security/cookie-analyzer.js"},
  {id:"referrer-policy", category:"security", subcategory:"web", name:"Referrer Policy Builder", icon:"share", description:"Build a Referrer-Policy header value.", module:"../tools/security/referrer-policy.js"},
  {id:"permissions-policy", category:"security", subcategory:"web", name:"Permissions Policy Builder", icon:"tune", description:"Build a restrictive Permissions-Policy header.", module:"../tools/security/permissions-policy.js"},
  {id:"cors-builder", category:"security", subcategory:"web", name:"CORS Header Builder", icon:"public", description:"Generate common CORS response headers.", module:"../tools/security/cors-builder.js"},
  {id:"secret-scanner", category:"security", subcategory:"inspection", name:"Secret Scanner", icon:"manage_search", description:"Scan pasted text for common secret-shaped patterns.", module:"../tools/security/secret-scanner.js"},
  {id:"url-safety", category:"security", subcategory:"inspection", name:"URL Safety Inspector", icon:"link", description:"Inspect obvious URL properties before opening a link.", module:"../tools/security/url-safety.js"},
  {id:"password-pattern", category:"security", subcategory:"inspection", name:"Password Pattern Helper", icon:"pattern", description:"Check a password against a local strength checklist.", module:"../tools/security/password-pattern.js"},
  {id:"security-checklist", category:"security", subcategory:"habits", name:"Security Checklist", icon:"checklist", description:"Track a quick set of everyday security habits.", module:"../tools/security/security-checklist.js"},
  {id:"percentage", category:"basic", name:"Percentage Calculator", icon:"percent", description:"Calculate percentages quickly.", module:"../tools/basic/percentage.js"},
  {id:"age-calculator", category:"basic", name:"Age Calculator", icon:"calendar", description:"Calculate age from a birth date.", module:"../tools/basic/age-calculator.js"},
  {id:"discount-calculator", category:"basic", name:"Discount Calculator", icon:"percent", description:"Calculate savings and final price.", module:"../tools/basic/discount-calculator.js"},
  {id:"tip-calculator", category:"basic", name:"Tip Calculator", icon:"percent", description:"Calculate tip, total and per-person cost.", module:"../tools/basic/tip-calculator.js"},
  {id:"average-calculator", category:"basic", name:"Average Calculator", icon:"calculator", description:"Find count, sum and average.", module:"../tools/basic/average-calculator.js"},
  {id:"ratio-simplifier", category:"basic", name:"Ratio Simplifier", icon:"calculator", description:"Reduce ratios to simplest form.", module:"../tools/basic/ratio-simplifier.js"},
  {id:"fraction-calculator", category:"basic", name:"Fraction Calculator", icon:"calculator", description:"Add, subtract, multiply or divide fractions.", module:"../tools/basic/fraction-calculator.js"},
  {id:"random-number", category:"basic", name:"Random Number Generator", icon:"star", description:"Generate random integers in a range.", module:"../tools/basic/random-number.js"},
  {id:"random-choice", category:"basic", name:"Random Choice Picker", icon:"star", description:"Pick one option from a list.", module:"../tools/basic/random-choice.js"},
  {id:"dice-roller", category:"basic", name:"Dice Roller", icon:"star", description:"Roll customizable dice locally.", module:"../tools/basic/dice-roller.js"},
  {id:"counter", category:"basic", name:"Counter", icon:"calculator", description:"A simple increment, decrement and reset counter.", module:"../tools/basic/counter.js"},
  {id:"stopwatch", category:"basic", name:"Stopwatch", icon:"clock", description:"Track elapsed time with laps.", module:"../tools/basic/stopwatch.js"},
  {id:"number-formatter", category:"basic", name:"Number Formatter", icon:"calculator", description:"Format numbers with thousands separators and decimals.", module:"../tools/basic/number-formatter.js"},
  {id:"roman-numeral", category:"basic", name:"Roman Numeral Converter", icon:"text", description:"Convert numbers to Roman numerals.", module:"../tools/basic/roman-numeral.js"},
  {id:"number-to-words", category:"basic", name:"Number to Words", icon:"text", description:"Convert integers into English words.", module:"../tools/basic/number-to-words.js"},
  {id:"word-counter", category:"text", name:"Word Counter", icon:"text", description:"Count words, characters and lines.", module:"../tools/text/word-counter.js"},
  {id:"character-counter", category:"text", name:"Character Counter", icon:"text", description:"Count characters and UTF-8 bytes.", module:"../tools/text/character-counter.js"},
  {id:"case-converter", category:"text", name:"Case Converter", icon:"text", description:"Convert text between common cases.", module:"../tools/text/case-converter.js"},
  {id:"remove-duplicate-lines", category:"text", name:"Remove Duplicate Lines", icon:"check", description:"Remove repeated lines while preserving order.", module:"../tools/text/remove-duplicate-lines.js"},
  {id:"sort-lines", category:"text", name:"Sort Lines", icon:"text", description:"Sort lines alphabetically, numerically or by length.", module:"../tools/text/sort-lines.js"},
  {id:"reverse-text", category:"text", name:"Reverse Text", icon:"text", description:"Reverse characters, words or lines.", module:"../tools/text/reverse-text.js"},
  {id:"trim-lines", category:"text", name:"Trim Lines", icon:"text", description:"Trim whitespace from every line.", module:"../tools/text/trim-lines.js"},
  {id:"remove-blank-lines", category:"text", name:"Remove Blank Lines", icon:"check", description:"Remove empty lines from text.", module:"../tools/text/remove-blank-lines.js"},
  {id:"find-replace", category:"text", name:"Find & Replace", icon:"search", description:"Find and replace text locally.", module:"../tools/text/find-replace.js"},
  {id:"line-counter", category:"text", name:"Line Counter", icon:"text", description:"Count total and non-empty lines.", module:"../tools/text/line-counter.js"},
  {id:"sentence-counter", category:"text", name:"Sentence Counter", icon:"text", description:"Count sentences in a passage.", module:"../tools/text/sentence-counter.js"},
  {id:"reading-time", category:"text", name:"Reading Time Calculator", icon:"clock", description:"Estimate reading time from text.", module:"../tools/text/reading-time.js"},
  {id:"extract-emails", category:"text", name:"Email Extractor", icon:"at", description:"Extract unique email addresses.", module:"../tools/text/extract-emails.js"},
  {id:"extract-urls", category:"text", name:"URL Extractor", icon:"link", description:"Extract HTTP and HTTPS URLs.", module:"../tools/text/extract-urls.js"},
  {id:"extract-hashtags", category:"text", name:"Hashtag Extractor", icon:"text", description:"Extract unique hashtags.", module:"../tools/text/extract-hashtags.js"},
  {id:"slug-generator", category:"text", name:"Slug Generator", icon:"text", description:"Turn titles into clean URL slugs.", module:"../tools/text/slug-generator.js"},
  {id:"morse-code", category:"text", name:"Morse Code Converter", icon:"text", description:"Encode text to Morse or decode Morse.", module:"../tools/text/morse-code.js"},
  {id:"url-encode", category:"text", name:"URL Encoder / Decoder", icon:"link", description:"Encode or decode URL components.", module:"../tools/text/url-encode.js"},
  {id:"lorem-ipsum", category:"text", name:"Lorem Ipsum Generator", icon:"text", description:"Generate placeholder paragraphs locally.", module:"../tools/text/lorem-ipsum.js"},
  {id:"markdown-preview", category:"text", name:"Markdown Preview", icon:"text", description:"Preview a small set of Markdown syntax.", module:"../tools/text/markdown-preview.js"},
  {id:"whitespace-cleaner", category:"text", name:"Whitespace Cleaner", icon:"broom", description:"Clean repeated spaces, tabs and blank lines.", module:"../tools/text/whitespace-cleaner.js"},
  {id:"json-formatter", category:"developer", subcategory:"data", name:"JSON Formatter", icon:"code", description:"Format, validate and inspect JSON.", module:"../tools/developer/json-formatter.js"},
  {id:"json-validator", category:"developer", subcategory:"data", name:"JSON Validator", icon:"check", description:"Validate JSON and show precise parse errors.", module:"../tools/developer/json-validator.js"},
  {id:"json-minifier", category:"developer", subcategory:"data", name:"JSON Minifier", icon:"compress", description:"Minify JSON without changing its data.", module:"../tools/developer/json-minifier.js"},
  {id:"json-yaml", category:"developer", subcategory:"data", name:"JSON ↔ YAML", icon:"swap", description:"Convert JSON and a practical YAML subset locally.", module:"../tools/developer/json-yaml.js"},
  {id:"yaml-formatter", category:"developer", subcategory:"data", name:"YAML Formatter", icon:"code", description:"Format common YAML data with readable indentation.", module:"../tools/developer/yaml-formatter.js"},
  {id:"xml-formatter", category:"developer", subcategory:"data", name:"XML Formatter", icon:"code", description:"Pretty-print XML documents in your browser.", module:"../tools/developer/xml-formatter.js"},
  {id:"xml-validator", category:"developer", subcategory:"data", name:"XML Validator", icon:"check", description:"Check XML structure and parser errors.", module:"../tools/developer/xml-validator.js"},
  {id:"csv-json", category:"developer", subcategory:"data", name:"CSV ↔ JSON", icon:"table", description:"Convert CSV rows to JSON and JSON arrays back to CSV.", module:"../tools/developer/csv-json.js"},
  {id:"toml-formatter", category:"developer", subcategory:"data", name:"TOML Formatter", icon:"code", description:"Format common TOML configuration data.", module:"../tools/developer/toml-formatter.js"},
  {id:"base64", category:"developer", subcategory:"encoding", name:"Base64 Encoder / Decoder", icon:"code", description:"Encode text to Base64 or decode Base64 to text.", module:"../tools/developer/base64.js"},
  {id:"url-encoder", category:"developer", subcategory:"encoding", name:"URL Encoder / Decoder", icon:"link", description:"Encode or decode URL components and full URLs.", module:"../tools/developer/url-encoder.js"},
  {id:"html-entities", category:"developer", subcategory:"encoding", name:"HTML Entity Encoder / Decoder", icon:"code", description:"Convert HTML entities to readable text and back.", module:"../tools/developer/html-entities.js"},
  {id:"unicode", category:"developer", subcategory:"encoding", name:"Unicode Converter", icon:"text", description:"Inspect and convert Unicode code points and text.", module:"../tools/developer/unicode.js"},
  {id:"hex", category:"developer", subcategory:"encoding", name:"Hex Encoder / Decoder", icon:"code", description:"Convert text to hexadecimal and back.", module:"../tools/developer/hex.js"},
  {id:"binary", category:"developer", subcategory:"encoding", name:"Binary ↔ Text", icon:"code", description:"Convert text to binary and binary back to text.", module:"../tools/developer/binary.js"},
  {id:"url-parser", category:"developer", subcategory:"web", name:"URL Parser", icon:"link", description:"Inspect protocol, host, path, query and fragments.", module:"../tools/developer/url-parser.js"},
  {id:"query-parser", category:"developer", subcategory:"web", name:"Query String Parser", icon:"search", description:"Parse and edit URL query parameters.", module:"../tools/developer/query-parser.js"},
  {id:"jwt-decoder", category:"developer", subcategory:"web", name:"JWT Decoder", icon:"key", description:"Decode JWT headers and payloads locally.", module:"../tools/developer/jwt-decoder.js"},
  {id:"http-status", category:"developer", subcategory:"web", name:"HTTP Status Code Reference", icon:"info", description:"Search common HTTP status codes and meanings.", module:"../tools/developer/http-status.js"},
  {id:"http-headers", category:"developer", subcategory:"web", name:"HTTP Header Parser", icon:"code", description:"Parse raw HTTP headers into structured key-value data.", module:"../tools/developer/http-headers.js"},
  {id:"user-agent", category:"developer", subcategory:"web", name:"User-Agent Parser", icon:"language", description:"Inspect browser and platform information from a user-agent string.", module:"../tools/developer/user-agent.js"},
  {id:"mime-types", category:"developer", subcategory:"web", name:"MIME Type Lookup", icon:"file", description:"Look up common MIME types and file extensions.", module:"../tools/developer/mime-types.js"},
  {id:"color-converter", category:"developer", subcategory:"web", name:"Color Converter", icon:"palette", description:"Pick colors and inspect HEX, RGB, HSL, HSV and CMYK values.", module:"../tools/developer/color-converter.js"},
  {id:"markdown-editor", category:"developer", subcategory:"code", name:"Markdown Editor", icon:"edit", description:"Write Markdown with a live preview.", module:"../tools/developer/markdown-editor.js"},
  {id:"html-formatter", category:"developer", subcategory:"code", name:"HTML Formatter", icon:"code", description:"Format HTML with readable indentation.", module:"../tools/developer/html-formatter.js"},
  {id:"css-formatter", category:"developer", subcategory:"code", name:"CSS Formatter", icon:"code", description:"Format CSS with readable indentation.", module:"../tools/developer/css-formatter.js"},
  {id:"javascript-formatter", category:"developer", subcategory:"code", name:"JavaScript Formatter", icon:"code", description:"Format common JavaScript code locally.", module:"../tools/developer/javascript-formatter.js"},
  {id:"javascript-minifier", category:"developer", subcategory:"code", name:"JavaScript Minifier", icon:"compress", description:"Minify common JavaScript without external services.", module:"../tools/developer/javascript-minifier.js"},
  {id:"sql-formatter", category:"developer", subcategory:"code", name:"SQL Formatter", icon:"database", description:"Format SQL queries for readability.", module:"../tools/developer/sql-formatter.js"},
  {id:"sql-minifier", category:"developer", subcategory:"code", name:"SQL Minifier", icon:"compress", description:"Compact SQL whitespace for easier transport.", module:"../tools/developer/sql-minifier.js"},
  {id:"code-diff", category:"developer", subcategory:"code", name:"Code Diff", icon:"compare", description:"Compare two code snippets line by line.", module:"../tools/developer/code-diff.js"},
  {id:"text-diff", category:"developer", subcategory:"code", name:"Text Diff", icon:"compare", description:"Compare two text blocks and highlight changes.", module:"../tools/developer/text-diff.js"},
  {id:"regex-tester", category:"developer", subcategory:"code", name:"Regex Tester", icon:"search", description:"Test regular expressions against sample text.", module:"../tools/developer/regex-tester.js"},
  {id:"uuid", category:"developer", subcategory:"identifiers", name:"UUID Generator", icon:"id", description:"Generate UUID v4 identifiers locally.", module:"../tools/developer/uuid.js"},
  {id:"ulid", category:"developer", subcategory:"identifiers", name:"ULID Generator", icon:"id", description:"Generate sortable ULIDs locally.", module:"../tools/developer/ulid.js"},
  {id:"nanoid", category:"developer", subcategory:"identifiers", name:"Nano ID Generator", icon:"id", description:"Generate compact random identifiers locally.", module:"../tools/developer/nanoid.js"},
  {id:"random-string", category:"developer", subcategory:"identifiers", name:"Random String Generator", icon:"shuffle", description:"Generate secure random strings in your browser.", module:"../tools/developer/random-string.js"},
  {id:"test-data", category:"developer", subcategory:"identifiers", name:"Test Data Generator", icon:"database", description:"Generate realistic-looking local test records.", module:"../tools/developer/test-data.js"},
  {id:"unix-timestamp", category:"developer", subcategory:"time", name:"Unix Timestamp Converter", icon:"clock", description:"Convert Unix timestamps and dates.", module:"../tools/developer/unix-timestamp.js"},
  {id:"iso-date", category:"developer", subcategory:"time", name:"ISO 8601 Converter", icon:"calendar", description:"Convert dates to ISO 8601 strings and back.", module:"../tools/developer/iso-date.js"},
  {id:"date-timestamp", category:"developer", subcategory:"time", name:"Date ↔ Timestamp", icon:"calendar", description:"Convert local dates and times to Unix timestamps.", module:"../tools/developer/date-timestamp.js"},
  {id:"cron-helper", category:"developer", subcategory:"time", name:"Cron Expression Helper", icon:"schedule", description:"Inspect common five-field cron expressions.", module:"../tools/developer/cron-helper.js"},
  {id:"hash-generator", category:"developer", subcategory:"hashing", name:"Hash Generator", icon:"key", description:"Generate MD5, SHA-1, SHA-256 and SHA-512 hashes.", module:"../tools/developer/hash-generator.js"},
  {id:"hmac-generator", category:"developer", subcategory:"hashing", name:"HMAC Generator", icon:"key", description:"Generate HMAC signatures with Web Crypto.", module:"../tools/developer/hmac-generator.js"},
  {id:"checksum", category:"developer", subcategory:"hashing", name:"Checksum Generator", icon:"check", description:"Generate cryptographic checksums for text.", module:"../tools/developer/checksum.js"},
];

export function getCategory(id){ return categories.find(c=>c.id===id); }
export function getTool(id){ return tools.find(t=>t.id===id); }
export function toolsForCategory(id){ return tools.filter(t=>t.category===id); }
