export const categories = [
  { id:"basic", name:"Basic", icon:"build", description:"Everyday quick tools, made fast" },
  { id:"text", name:"Text", icon:"text", description:"Write, clean & transform text" },
  { id:"calculators", name:"Calculators", icon:"calculator", description:"Math and everyday calculations" },
  { id:"converters", name:"Converters", icon:"swap", description:"Convert units and formats" },
  { id:"developer", name:"Developer", icon:"code", description:"Tools for code, data and web work", subcategories:[
    {id:"data",name:"Data & Serialization",icon:"data-object"},
    {id:"encoding",name:"Encoding & Decoding",icon:"code"},
    {id:"web",name:"Web",icon:"language"},
    {id:"code",name:"Code",icon:"code-block"},
    {id:"identifiers",name:"Identifiers & Data",icon:"id"},
    {id:"time",name:"Time",icon:"clock"},
    {id:"hashing",name:"Hashing & Checksums",icon:"key"}
  ] },
  { id:"utilities", name:"Utilities", icon:"handyman", description:"Fun, practical and browser-native tools", subcategories:[
    {id:"time",name:"Date & Time",icon:"schedule"},
    {id:"random",name:"Random & Generators",icon:"shuffle"},
    {id:"planning",name:"Money & Planning",icon:"savings"},
    {id:"browser",name:"Browser & Device",icon:"devices"},
    {id:"creative",name:"Creative & Voice",icon:"palette"},
    {id:"games",name:"Games & Fun",icon:"sports_esports"}
  ] },
  { id:"security", name:"Security", icon:"lock", description:"Defensive security, privacy and integrity tools", subcategories:[
    {id:"access",name:"Passwords & Access",icon:"key"},
    {id:"integrity",name:"Integrity & Hashing",icon:"fingerprint"},
    {id:"web",name:"Web Security",icon:"public"},
    {id:"inspection",name:"Inspection & Privacy",icon:"policy"},
    {id:"habits",name:"Security Habits",icon:"checklist"}
  ] },
,
  { id:"pdf", name:"PDF Editor", icon:"picture_as_pdf", description:"View, edit and organize PDF documents", kind:"product" }
];


export const tools = [
  {id:"world-clock", category:"utilities", subcategory:"time", name:"World Clock", icon:"schedule", description:"Live clocks for popular cities with automatic updates.", module:"../tools/utilities/world-clock.js"},
  {id:"timezone-converter", category:"utilities", subcategory:"time", name:"Time Zone Converter", icon:"public", description:"Convert a date and time between common time zones.", module:"../tools/utilities/timezone-converter.js"},
  {id:"date-difference", category:"utilities", subcategory:"time", name:"Date Difference", icon:"date_range", description:"Measure the span between two dates.", module:"../tools/utilities/date-difference.js"},
  {id:"countdown", category:"utilities", subcategory:"time", name:"Countdown Timer", icon:"timer", description:"Run a live countdown to any date and time.", module:"../tools/utilities/countdown.js"},
  {id:"pomodoro", category:"utilities", subcategory:"time", name:"Pomodoro Timer", icon:"timer", description:"Focus and break cycles with a session counter.", module:"../tools/utilities/pomodoro.js"},
  {id:"calendar-generator", category:"utilities", subcategory:"time", name:"Calendar Generator", icon:"calendar_month", description:"Generate a clean month calendar for any year.", module:"../tools/utilities/calendar-generator.js"},
  {id:"business-days", category:"utilities", subcategory:"time", name:"Business Days Calculator", icon:"work_history", description:"Count weekdays between two dates.", module:"../tools/utilities/business-days.js"},
  {id:"week-number", category:"utilities", subcategory:"time", name:"Week Number", icon:"view_week", description:"Get ISO week and day-of-year information.", module:"../tools/utilities/week-number.js"},
  {id:"shuffle-list", category:"utilities", subcategory:"random", name:"Shuffle List", icon:"shuffle", description:"Randomize a list while keeping every item.", module:"../tools/utilities/shuffle-list.js"},
  {id:"fortune-generator", category:"utilities", subcategory:"random", name:"Fortune Generator", icon:"auto_awesome", description:"Reveal a playful random answer to a question.", module:"../tools/utilities/fortune-generator.js"},
  {id:"coin-flip", category:"utilities", subcategory:"random", name:"Coin Flip", icon:"toll", description:"Flip one coin or run a batch of flips.", module:"../tools/utilities/coin-flip.js"},
  {id:"spin-wheel", category:"utilities", subcategory:"random", name:"Spin the Wheel", icon:"casino", description:"Spin a colorful wheel to choose one option.", module:"../tools/utilities/spin-wheel.js"},
  {id:"password-generator", category:"utilities", subcategory:"random", name:"Password Generator", icon:"password", description:"Generate strong local passwords with configurable character sets.", module:"../tools/utilities/password-generator.js"},
  {id:"random-color", category:"utilities", subcategory:"random", name:"Random Color", icon:"palette", description:"Generate and copy random HEX colors.", module:"../tools/utilities/random-color.js"},
  {id:"random-teams", category:"utilities", subcategory:"random", name:"Random Team Generator", icon:"groups", description:"Shuffle people into balanced teams.", module:"../tools/utilities/random-teams.js"},
  {id:"number-sequence", category:"utilities", subcategory:"random", name:"Number Sequence Generator", icon:"123", description:"Create arithmetic or geometric number sequences.", module:"../tools/utilities/number-sequence.js"},
  {id:"split-bill", category:"utilities", subcategory:"planning", name:"Split Bill", icon:"receipt_long", description:"Split a bill with people and tip included.", module:"../tools/utilities/split-bill.js"},
  {id:"tip-planner", category:"utilities", subcategory:"planning", name:"Tip Planner", icon:"volunteer_activism", description:"Compare common tip percentages at a glance.", module:"../tools/utilities/tip-planner.js"},
  {id:"discount-breakdown", category:"utilities", subcategory:"planning", name:"Discount Breakdown", icon:"percent", description:"See savings, discounted price and optional tax.", module:"../tools/utilities/discount-breakdown.js"},
  {id:"savings-goal", category:"utilities", subcategory:"planning", name:"Savings Goal", icon:"savings", description:"Calculate the monthly amount needed for a target.", module:"../tools/utilities/savings-goal.js"},
  {id:"budget-split", category:"utilities", subcategory:"planning", name:"Budget Split", icon:"account_balance_wallet", description:"Split a budget into practical buckets.", module:"../tools/utilities/budget-split.js"},
  {id:"fuel-cost", category:"utilities", subcategory:"planning", name:"Fuel Cost", icon:"local_gas_station", description:"Estimate fuel usage and trip cost.", module:"../tools/utilities/fuel-cost.js"},
  {id:"grade-tracker", category:"utilities", subcategory:"planning", name:"Grade Tracker", icon:"school", description:"Calculate weighted marks from assessments.", module:"../tools/utilities/grade-tracker.js"},
  {id:"aspect-ratio", category:"utilities", subcategory:"planning", name:"Aspect Ratio Helper", icon:"aspect_ratio", description:"Reduce dimensions and calculate matching sizes.", module:"../tools/utilities/aspect-ratio.js"},
  {id:"browser-info", category:"utilities", subcategory:"browser", name:"Browser Info", icon:"language", description:"Inspect browser-provided session information.", module:"../tools/utilities/browser-info.js"},
  {id:"device-info", category:"utilities", subcategory:"browser", name:"Device Info", icon:"devices", description:"Inspect viewport, screen, touch and pixel details.", module:"../tools/utilities/device-info.js"},
  {id:"network-status", category:"utilities", subcategory:"browser", name:"Network Status", icon:"wifi", description:"Inspect online state and connection hints.", module:"../tools/utilities/network-status.js"},
  {id:"screen-info", category:"utilities", subcategory:"browser", name:"Screen Info", icon:"monitor", description:"Inspect display size, orientation and pixel ratio.", module:"../tools/utilities/screen-info.js"},
  {id:"keyboard-tester", category:"utilities", subcategory:"browser", name:"Keyboard Tester", icon:"keyboard", description:"Test keys, codes, modifiers and recent presses.", module:"../tools/utilities/keyboard-tester.js"},
  {id:"fullscreen-tester", category:"utilities", subcategory:"browser", name:"Fullscreen Tester", icon:"fullscreen", description:"Test browser fullscreen support.", module:"../tools/utilities/fullscreen-tester.js"},
  {id:"url-inspector", category:"utilities", subcategory:"browser", name:"URL Inspector", icon:"link", description:"Break a URL into its useful parts.", module:"../tools/utilities/url-inspector.js"},
  {id:"color-palette", category:"utilities", subcategory:"creative", name:"Color Palette", icon:"palette", description:"Build a light-to-dark palette from a base color.", module:"../tools/utilities/color-palette.js"},
  {id:"gradient-generator", category:"utilities", subcategory:"creative", name:"Gradient Generator", icon:"gradient", description:"Create and copy ready-to-use CSS gradients.", module:"../tools/utilities/gradient-generator.js"},
  {id:"emoji-picker", category:"utilities", subcategory:"creative", name:"Emoji Picker", icon:"emoji_emotions", description:"Browse and copy handy emojis quickly.", module:"../tools/utilities/emoji-picker.js"},
  {id:"text-to-speech", category:"utilities", subcategory:"creative", name:"Text to Speech", icon:"volume_up", description:"Read text aloud using the browser voice engine.", module:"../tools/utilities/text-to-speech.js"},
  {id:"higher-lower", category:"utilities", subcategory:"games", name:"Higher or Lower", icon:"swap_vert", description:"Predict whether the next number will be higher or lower.", module:"../tools/utilities/higher-lower.js"},
  {id:"reaction-timer", category:"utilities", subcategory:"games", name:"Reaction Timer", icon:"bolt", description:"Measure how quickly you react to the signal.", module:"../tools/utilities/reaction-timer.js"},
  {id:"scoreboard", category:"utilities", subcategory:"games", name:"Scoreboard", icon:"leaderboard", description:"Touch-friendly scoring for games, quizzes and practice.", module:"../tools/utilities/scoreboard.js"},
  {id:"typing-speed", category:"utilities", subcategory:"games", name:"Typing Speed", icon:"keyboard", description:"Measure WPM and typing accuracy in a 30-second test.", module:"../tools/utilities/typing-speed.js"},
  {id:"simple-interest", category:"calculators", name:"Simple Interest Calculator", icon:"percent", description:"Calculate simple interest and total amount.", module:"../tools/calculators/simple-interest.js"},
  {id:"compound-interest", category:"calculators", name:"Compound Interest Calculator", icon:"percent", description:"Calculate compound growth and interest.", module:"../tools/calculators/compound-interest.js"},
  {id:"emi-calculator", category:"calculators", name:"EMI Calculator", icon:"calculator", description:"Calculate monthly loan payments.", module:"../tools/calculators/emi-calculator.js"},
  {id:"loan-payment", category:"calculators", name:"Loan Payment Calculator", icon:"calculator", description:"Calculate periodic loan payments.", module:"../tools/calculators/loan-payment.js"},
  {id:"mean-median-mode", category:"calculators", name:"Mean Median Mode", icon:"calculator", description:"Find mean, median and mode.", module:"../tools/calculators/mean-median-mode.js"},
  {id:"gcd-lcm", category:"calculators", name:"GCD & LCM Calculator", icon:"calculator", description:"Calculate greatest common divisor and least common multiple.", module:"../tools/calculators/gcd-lcm.js"},
  {id:"prime-checker", category:"calculators", name:"Prime Number Checker", icon:"calculator", description:"Check whether an integer is prime.", module:"../tools/calculators/prime-checker.js"},
  {id:"quadratic-solver", category:"calculators", name:"Quadratic Equation Solver", icon:"calculator", description:"Solve quadratic equations.", module:"../tools/calculators/quadratic-solver.js"},
  {id:"pythagorean", category:"calculators", name:"Pythagorean Theorem", icon:"calculator", description:"Calculate a missing right-triangle side.", module:"../tools/calculators/pythagorean.js"},
  {id:"speed-distance-time", category:"calculators", name:"Speed Distance Time", icon:"calculator", description:"Calculate distance from speed and time.", module:"../tools/calculators/speed-distance-time.js"},
  {id:"probability", category:"calculators", name:"Probability Calculator", icon:"calculator", description:"Calculate simple probability.", module:"../tools/calculators/probability.js"},
  {id:"area-volume", category:"calculators", name:"Area & Volume Calculator", icon:"calculator", description:"Calculate common geometric areas and volumes.", module:"../tools/calculators/area-volume.js"},
  {id:"percent-change", category:"calculators", name:"Percent Change Calculator", icon:"percent", description:"Calculate percentage increase or decrease.", module:"../tools/calculators/percent-change.js"},
  {id:"graph-calculator", category:"calculators", name:"Graph Calculator", icon:"show_chart", description:"Plot mathematical functions on a live graph.", module:"../tools/calculators/graph-calculator.js"},
  {id:"length-converter", category:"converters", name:"Length Converter", icon:"swap", description:"Convert common length units.", module:"../tools/converters/length.js"},
  {id:"mass-converter", category:"converters", name:"Mass Converter", icon:"swap", description:"Convert weight and mass units.", module:"../tools/converters/mass.js"},
  {id:"temperature-converter", category:"converters", name:"Temperature Converter", icon:"swap", description:"Convert Celsius, Fahrenheit and Kelvin.", module:"../tools/converters/temperature.js"},
  {id:"area-converter", category:"converters", name:"Area Converter", icon:"swap", description:"Convert common area units.", module:"../tools/converters/area.js"},
  {id:"volume-converter", category:"converters", name:"Volume Converter", icon:"swap", description:"Convert volume and capacity units.", module:"../tools/converters/volume.js"},
  {id:"speed-converter", category:"converters", name:"Speed Converter", icon:"swap", description:"Convert speed units.", module:"../tools/converters/speed.js"},
  {id:"time-converter", category:"converters", name:"Time Converter", icon:"swap", description:"Convert time units.", module:"../tools/converters/time.js"},
  {id:"data-converter", category:"converters", name:"Data Storage Converter", icon:"swap", description:"Convert bytes and binary storage units.", module:"../tools/converters/data.js"},
  {id:"pressure-converter", category:"converters", name:"Pressure Converter", icon:"swap", description:"Convert pressure units.", module:"../tools/converters/pressure.js"},
  {id:"energy-converter", category:"converters", name:"Energy Converter", icon:"swap", description:"Convert energy units.", module:"../tools/converters/energy.js"},
  {id:"power-converter", category:"converters", name:"Power Converter", icon:"swap", description:"Convert power units.", module:"../tools/converters/power.js"},
  {id:"angle-converter", category:"converters", name:"Angle Converter", icon:"swap", description:"Convert degrees, radians, gradians and turns.", module:"../tools/converters/angle.js"},
  {id:"frequency-converter", category:"converters", name:"Frequency Converter", icon:"swap", description:"Convert frequency units.", module:"../tools/converters/frequency.js"},
  {id:"number-base-converter", category:"converters", name:"Number Base Converter", icon:"swap", description:"Convert numbers between bases 2, 8, 10 and 16.", module:"../tools/converters/number-base.js"},
  {id:"currency-converter", category:"converters", name:"Currency Converter", icon:"currency_exchange", description:"Convert currencies using current reference rates.", module:"../tools/converters/currency.js"},
  {id:"password-strength", category:"security", subcategory:"access", name:"Password Strength Checker", icon:"key", description:"Evaluate password strength locally without uploading it.", module:"../tools/security/password-strength.js"},
  {id:"passphrase", category:"security", subcategory:"access", name:"Passphrase Generator", icon:"password", description:"Generate memorable multi-word passphrases locally.", module:"../tools/security/passphrase.js"},
  {id:"secure-token", category:"security", subcategory:"access", name:"Secure Token Generator", icon:"vpn_key", description:"Generate random URL-safe tokens with Web Crypto.", module:"../tools/security/secure-token.js"},
  {id:"pin-strength", category:"security", subcategory:"access", name:"PIN Strength Checker", icon:"dialpad", description:"Spot obvious weak patterns in numeric PINs.", module:"../tools/security/pin-strength.js"},
  {id:"recovery-codes", category:"security", subcategory:"access", name:"Recovery Code Generator", icon:"confirmation_number", description:"Generate backup codes for accounts you control.", module:"../tools/security/recovery-codes.js"},
  {id:"totp-generator", category:"security", subcategory:"access", name:"TOTP Code Generator", icon:"security", description:"Generate a time-based code from a Base32 secret.", module:"../tools/security/totp-generator.js"},
  {id:"sha-hash", category:"security", subcategory:"integrity", name:"SHA Hash Generator", icon:"fingerprint", description:"Calculate SHA-1, SHA-256 or SHA-512 locally.", module:"../tools/security/sha-hash.js"},
  {id:"sri-generator", category:"security", subcategory:"integrity", name:"SRI Hash Generator", icon:"verified", description:"Create a Subresource Integrity hash from asset contents.", module:"../tools/security/sri-generator.js"},
  {id:"file-hash", category:"security", subcategory:"integrity", name:"File Hash Checker", icon:"description", description:"Hash a local file in your browser without uploading it.", module:"../tools/security/file-hash.js"},
  {id:"hash-compare", category:"security", subcategory:"integrity", name:"Hash Compare", icon:"compare", description:"Compare two hexadecimal digests locally.", module:"../tools/security/hash-compare.js"},
  {id:"csp-builder", category:"security", subcategory:"web", name:"CSP Builder", icon:"policy", description:"Build a Content-Security-Policy header from common directives.", module:"../tools/security/csp-builder.js"},
  {id:"security-headers", category:"security", subcategory:"web", name:"Security Headers Analyzer", icon:"http", description:"Inspect pasted response headers for useful protections.", module:"../tools/security/security-headers.js"},
  {id:"cookie-analyzer", category:"security", subcategory:"web", name:"Cookie Security Analyzer", icon:"cookie", description:"Inspect pasted Set-Cookie lines for common flags.", module:"../tools/security/cookie-analyzer.js"},
  {id:"referrer-policy", category:"security", subcategory:"web", name:"Referrer Policy Builder", icon:"share", description:"Build a Referrer-Policy header value.", module:"../tools/security/referrer-policy.js"},
  {id:"permissions-policy", category:"security", subcategory:"web", name:"Permissions Policy Builder", icon:"tune", description:"Build a restrictive Permissions-Policy header.", module:"../tools/security/permissions-policy.js"},
  {id:"cors-builder", category:"security", subcategory:"web", name:"CORS Header Builder", icon:"public", description:"Generate common CORS response headers.", module:"../tools/security/cors-builder.js"},
  {id:"secret-scanner", category:"security", subcategory:"inspection", name:"Secret Scanner", icon:"manage_search", description:"Scan pasted text for common secret-shaped patterns.", module:"../tools/security/secret-scanner.js"},
  {id:"url-safety", category:"security", subcategory:"inspection", name:"URL Safety Inspector", icon:"link", description:"Inspect obvious URL properties before opening a link.", module:"../tools/security/url-safety.js"},
  {id:"password-pattern", category:"security", subcategory:"inspection", name:"Password Pattern Helper", icon:"pattern", description:"Check a password against a local strength checklist.", module:"../tools/security/password-pattern.js"},
  {id:"security-checklist", category:"security", subcategory:"habits", name:"Security Checklist", icon:"checklist", description:"Track a quick set of everyday security habits.", module:"../tools/security/security-checklist.js"},

export function getCategory(id){ return categories.find(c=>c.id===id); }
export function getTool(id){ return tools.find(t=>t.id===id); }
export function toolsForCategory(id){ return tools.filter(t=>t.category===id); }
