export const categories = [
  { id:"basic", name:"Basic", icon:"build", description:"Everyday quick tools, made fast" },
  { id:"text", name:"Text", icon:"text", description:"Write, clean & transform text" },
  { id:"calculators", name:"Calculators", icon:"calculator", description:"Math and everyday calculations" },
  { id:"converters", name:"Converters", icon:"swap", description:"Convert units and formats" },
  { id:"developer", name:"Developer", icon:"code", description:"Tools for code and data" },
  { id:"image", name:"Image", icon:"image", description:"Fast browser-based image tools" },
  { id:"pdf", name:"PDF", icon:"pdf", description:"PDF utilities" },
  { id:"documents", name:"Documents", icon:"folder", description:"Files, office and document tools" },
  { id:"security", name:"Security", icon:"lock", description:"Privacy and security utilities" },
];

export const tools = [
  {id:"percentage", category:"basic", name:"Percentage Calculator", icon:"percent", description:"Calculate percentages quickly.", module:"../tools/basic/percentage.js?v=18"},
  {id:"age-calculator", category:"basic", name:"Age Calculator", icon:"calendar", description:"Calculate age from a birth date.", module:"../tools/basic/age-calculator.js?v=18"},
  {id:"discount-calculator", category:"basic", name:"Discount Calculator", icon:"percent", description:"Calculate savings and final price.", module:"../tools/basic/discount-calculator.js?v=18"},
  {id:"tip-calculator", category:"basic", name:"Tip Calculator", icon:"percent", description:"Calculate tip, total and per-person cost.", module:"../tools/basic/tip-calculator.js?v=18"},
  {id:"average-calculator", category:"basic", name:"Average Calculator", icon:"calculator", description:"Find count, sum and average.", module:"../tools/basic/average-calculator.js?v=18"},
  {id:"ratio-simplifier", category:"basic", name:"Ratio Simplifier", icon:"calculator", description:"Reduce ratios to simplest form.", module:"../tools/basic/ratio-simplifier.js?v=18"},
  {id:"fraction-calculator", category:"basic", name:"Fraction Calculator", icon:"calculator", description:"Add, subtract, multiply or divide fractions.", module:"../tools/basic/fraction-calculator.js?v=18"},
  {id:"random-number", category:"basic", name:"Random Number Generator", icon:"star", description:"Generate random integers in a range.", module:"../tools/basic/random-number.js?v=18"},
  {id:"random-choice", category:"basic", name:"Random Choice Picker", icon:"star", description:"Pick one option from a list.", module:"../tools/basic/random-choice.js?v=18"},
  {id:"dice-roller", category:"basic", name:"Dice Roller", icon:"star", description:"Roll customizable dice locally.", module:"../tools/basic/dice-roller.js?v=18"},
  {id:"counter", category:"basic", name:"Counter", icon:"calculator", description:"A simple increment, decrement and reset counter.", module:"../tools/basic/counter.js?v=18"},
  {id:"stopwatch", category:"basic", name:"Stopwatch", icon:"clock", description:"Track elapsed time with laps.", module:"../tools/basic/stopwatch.js?v=18"},
  {id:"number-formatter", category:"basic", name:"Number Formatter", icon:"calculator", description:"Format numbers with thousands separators and decimals.", module:"../tools/basic/number-formatter.js?v=18"},
  {id:"roman-numeral", category:"basic", name:"Roman Numeral Converter", icon:"text", description:"Convert numbers to Roman numerals.", module:"../tools/basic/roman-numeral.js?v=18"},
  {id:"number-to-words", category:"basic", name:"Number to Words", icon:"text", description:"Convert integers into English words.", module:"../tools/basic/number-to-words.js?v=18"},
  {id:"word-counter", category:"text", name:"Word Counter", icon:"text", description:"Count words, characters and lines.", module:"../tools/text/word-counter.js?v=18"},
  {id:"character-counter", category:"text", name:"Character Counter", icon:"text", description:"Count characters and UTF-8 bytes.", module:"../tools/text/character-counter.js?v=18"},
  {id:"case-converter", category:"text", name:"Case Converter", icon:"text", description:"Convert text between common cases.", module:"../tools/text/case-converter.js?v=18"},
  {id:"remove-duplicate-lines", category:"text", name:"Remove Duplicate Lines", icon:"check", description:"Remove repeated lines while preserving order.", module:"../tools/text/remove-duplicate-lines.js?v=18"},
  {id:"sort-lines", category:"text", name:"Sort Lines", icon:"text", description:"Sort lines alphabetically, numerically or by length.", module:"../tools/text/sort-lines.js?v=18"},
  {id:"reverse-text", category:"text", name:"Reverse Text", icon:"text", description:"Reverse characters, words or lines.", module:"../tools/text/reverse-text.js?v=18"},
  {id:"trim-lines", category:"text", name:"Trim Lines", icon:"text", description:"Trim whitespace from every line.", module:"../tools/text/trim-lines.js?v=18"},
  {id:"remove-blank-lines", category:"text", name:"Remove Blank Lines", icon:"check", description:"Remove empty lines from text.", module:"../tools/text/remove-blank-lines.js?v=18"},
  {id:"find-replace", category:"text", name:"Find & Replace", icon:"search", description:"Find and replace text locally.", module:"../tools/text/find-replace.js?v=18"},
  {id:"line-counter", category:"text", name:"Line Counter", icon:"text", description:"Count total and non-empty lines.", module:"../tools/text/line-counter.js?v=18"},
  {id:"sentence-counter", category:"text", name:"Sentence Counter", icon:"text", description:"Count sentences in a passage.", module:"../tools/text/sentence-counter.js?v=18"},
  {id:"reading-time", category:"text", name:"Reading Time Calculator", icon:"clock", description:"Estimate reading time from text.", module:"../tools/text/reading-time.js?v=18"},
  {id:"extract-emails", category:"text", name:"Email Extractor", icon:"at", description:"Extract unique email addresses.", module:"../tools/text/extract-emails.js?v=18"},
  {id:"extract-urls", category:"text", name:"URL Extractor", icon:"link", description:"Extract HTTP and HTTPS URLs.", module:"../tools/text/extract-urls.js?v=18"},
  {id:"extract-hashtags", category:"text", name:"Hashtag Extractor", icon:"text", description:"Extract unique hashtags.", module:"../tools/text/extract-hashtags.js?v=18"},
  {id:"slug-generator", category:"text", name:"Slug Generator", icon:"text", description:"Turn titles into clean URL slugs.", module:"../tools/text/slug-generator.js?v=18"},
  {id:"morse-code", category:"text", name:"Morse Code Converter", icon:"text", description:"Encode text to Morse or decode Morse.", module:"../tools/text/morse-code.js?v=18"},
  {id:"url-encode", category:"text", name:"URL Encoder / Decoder", icon:"link", description:"Encode or decode URL components.", module:"../tools/text/url-encode.js?v=18"},
  {id:"lorem-ipsum", category:"text", name:"Lorem Ipsum Generator", icon:"text", description:"Generate placeholder paragraphs locally.", module:"../tools/text/lorem-ipsum.js?v=18"},
  {id:"markdown-preview", category:"text", name:"Markdown Preview", icon:"text", description:"Preview a small set of Markdown syntax.", module:"../tools/text/markdown-preview.js?v=18"},
  {id:"whitespace-cleaner", category:"text", name:"Whitespace Cleaner", icon:"broom", description:"Clean repeated spaces, tabs and blank lines.", module:"../tools/text/whitespace-cleaner.js?v=18"},
  {id:"json-formatter", category:"developer", name:"JSON Formatter", icon:"code", description:"Format and validate JSON.", module:"../tools/developer/json-formatter.js?v=18"},
  {id:"uuid", category:"developer", name:"UUID Generator", icon:"id", description:"Generate UUIDs locally.", module:"../tools/developer/uuid.js?v=18"},
  {id:"simple-interest", category:"calculators", name:"Simple Interest Calculator", icon:"percent", description:"Calculate simple interest and total amount.", module:"../tools/calculators/simple-interest.js?v=18"},
  {id:"compound-interest", category:"calculators", name:"Compound Interest Calculator", icon:"percent", description:"Calculate compound growth and interest.", module:"../tools/calculators/compound-interest.js?v=18"},
  {id:"emi-calculator", category:"calculators", name:"EMI Calculator", icon:"calculator", description:"Calculate monthly loan payments.", module:"../tools/calculators/emi-calculator.js?v=18"},
  {id:"loan-payment", category:"calculators", name:"Loan Payment Calculator", icon:"calculator", description:"Calculate periodic loan payments.", module:"../tools/calculators/loan-payment.js?v=18"},
  {id:"mean-median-mode", category:"calculators", name:"Mean Median Mode", icon:"calculator", description:"Find mean, median and mode.", module:"../tools/calculators/mean-median-mode.js?v=18"},
  {id:"gcd-lcm", category:"calculators", name:"GCD & LCM Calculator", icon:"calculator", description:"Calculate greatest common divisor and least common multiple.", module:"../tools/calculators/gcd-lcm.js?v=18"},
  {id:"prime-checker", category:"calculators", name:"Prime Number Checker", icon:"calculator", description:"Check whether an integer is prime.", module:"../tools/calculators/prime-checker.js?v=18"},
  {id:"quadratic-solver", category:"calculators", name:"Quadratic Equation Solver", icon:"calculator", description:"Solve quadratic equations.", module:"../tools/calculators/quadratic-solver.js?v=18"},
  {id:"pythagorean", category:"calculators", name:"Pythagorean Theorem", icon:"calculator", description:"Calculate a missing right-triangle side.", module:"../tools/calculators/pythagorean.js?v=18"},
  {id:"speed-distance-time", category:"calculators", name:"Speed Distance Time", icon:"calculator", description:"Calculate distance from speed and time.", module:"../tools/calculators/speed-distance-time.js?v=18"},
  {id:"probability", category:"calculators", name:"Probability Calculator", icon:"calculator", description:"Calculate simple probability.", module:"../tools/calculators/probability.js?v=18"},
  {id:"area-volume", category:"calculators", name:"Area & Volume Calculator", icon:"calculator", description:"Calculate common geometric areas and volumes.", module:"../tools/calculators/area-volume.js?v=18"},
  {id:"percent-change", category:"calculators", name:"Percent Change Calculator", icon:"percent", description:"Calculate percentage increase or decrease.", module:"../tools/calculators/percent-change.js?v=18"},
  {id:"length-converter", category:"converters", name:"Length Converter", icon:"swap", description:"Convert common length units.", module:"../tools/converters/length.js?v=18"},
  {id:"mass-converter", category:"converters", name:"Mass Converter", icon:"swap", description:"Convert weight and mass units.", module:"../tools/converters/mass.js?v=18"},
  {id:"temperature-converter", category:"converters", name:"Temperature Converter", icon:"swap", description:"Convert Celsius, Fahrenheit and Kelvin.", module:"../tools/converters/temperature.js?v=18"},
  {id:"area-converter", category:"converters", name:"Area Converter", icon:"swap", description:"Convert common area units.", module:"../tools/converters/area.js?v=18"},
  {id:"volume-converter", category:"converters", name:"Volume Converter", icon:"swap", description:"Convert volume and capacity units.", module:"../tools/converters/volume.js?v=18"},
  {id:"speed-converter", category:"converters", name:"Speed Converter", icon:"swap", description:"Convert speed units.", module:"../tools/converters/speed.js?v=18"},
  {id:"time-converter", category:"converters", name:"Time Converter", icon:"swap", description:"Convert time units.", module:"../tools/converters/time.js?v=18"},
  {id:"data-converter", category:"converters", name:"Data Storage Converter", icon:"swap", description:"Convert bytes and binary storage units.", module:"../tools/converters/data.js?v=18"},
  {id:"pressure-converter", category:"converters", name:"Pressure Converter", icon:"swap", description:"Convert pressure units.", module:"../tools/converters/pressure.js?v=18"},
  {id:"energy-converter", category:"converters", name:"Energy Converter", icon:"swap", description:"Convert energy units.", module:"../tools/converters/energy.js?v=18"},
  {id:"power-converter", category:"converters", name:"Power Converter", icon:"swap", description:"Convert power units.", module:"../tools/converters/power.js?v=18"},
  {id:"angle-converter", category:"converters", name:"Angle Converter", icon:"swap", description:"Convert degrees, radians, gradians and turns.", module:"../tools/converters/angle.js?v=18"},
  {id:"frequency-converter", category:"converters", name:"Frequency Converter", icon:"swap", description:"Convert frequency units.", module:"../tools/converters/frequency.js?v=18"},
  {id:"number-base-converter", category:"converters", name:"Number Base Converter", icon:"swap", description:"Convert numbers between bases 2, 8, 10 and 16.", module:"../tools/converters/number-base.js?v=18"},
  {id:"graph-calculator", category:"calculators", name:"Graph Calculator", icon:"show_chart", description:"Plot mathematical functions on a live graph.", module:"../tools/calculators/graph-calculator.js?v=18"},
  {id:"currency-converter", category:"converters", name:"Currency Converter", icon:"currency_exchange", description:"Convert currencies using current reference rates.", module:"../tools/converters/currency.js?v=18"},
];

export function getCategory(id){ return categories.find(c=>c.id===id); }
export function getTool(id){ return tools.find(t=>t.id===id); }
export function toolsForCategory(id){ return tools.filter(t=>t.category===id); }
